### ISSUE TITLE
Feature Request: Allow text based labels in charts

### ISSUE THREAD

**Issue by partingc** [jmcnamara/excel-writer-xlsx#102]
Allow setting `<c:auto val="0">` (ie force text based labels instead of auto detection or forced date)

Something like this would be nice (matches date_axis setting)
`$chart->set_x_axis( text_axis => 1 );`

I am using a perl script to create a system healthcheck excel workbook for Linux servers.  I have imported SAR, Syslog, and other log information and now want to generate charts.  The chart (with auto=1) see's that my time field includes the date and sets my horizontal axis to a minimum tick of 1 day.  Considering the data is in 10 minute increments this is a pain.

**Comment by jmcnamara** [comment]
Fixed in version 0.82.

Thanks for the report and input.

John.
