### ISSUE TITLE
Request: Conditional Formatting, Icon Sets

### ISSUE THREAD

**Issue by KevinGood** [jmcnamara/excel-writer-xlsx#116]
Hi John,
I want to say a HUGE thank you for your work on this massive time saving module!!!

In reading through the CPAN documentation on conditional formatting, it mentions that "Other types and parameters such as icon sets will be added in time." 

This is a feature that I would love to see added!

Thanks again!
Kevin

**Comment by jmcnamara** [comment]
Icon sets in conditional formatting have been added in Excel::Write::Excel 0.96.
