### ISSUE TITLE
Charts, and Tick Marks

### ISSUE THREAD

**Issue by KevinGood** [jmcnamara/excel-writer-xlsx#117]
I'm not sure if I'm missing something, but I don't seem to be able to set the interval between tick marks.  I am able to set the Interval unit (which sets the labels) but I have a line chart with 720 entries, and would like to set the tick marks to every 24 points.

**Comment by jmcnamara** [comment]
Added in version 0.87:

    $chart->set_x_axis( interval_tick => 2 );
