### ISSUE TITLE
Excel-Writer-XLSX 0.81

### ISSUE THREAD

**Issue by GayathriT** [jmcnamara/excel-writer-xlsx#119]
Hi All,

Please, give me a Suggesion.
We are having the Perl version of 5.8.4 at our workplace in Solaris 2.10.
Does it will support the higher version of the module Excel-Writer-XLSX like 0.81 ?!

Because, I have found in this below link as it does supports the module version 0.40 for our system.

http://matrix.cpantesters.org/?dist=Excel-Writer-XLSX;maxver=1

**Comment by jmcnamara** [comment]
Hi @GayathriT,

> Does it will support the higher version of the module Excel-Writer-XLSX like 0.81

I don't know. The easiest way to establish that would be to try it.

The minimum perl requirement for Excel::Writer::XLSX is 5.8.2. There are other module requirements as well which are listed in the [Makefile](http://cpansearch.perl.org/src/JMCNAMARA/Excel-Writer-XLSX-0.81/Makefile.PL).

Regards,

John
