### ISSUE TITLE
Uploading Excel file into MS Sharepoint Site via Perl HTTP::DAV

### ISSUE THREAD

**Issue by GayathriT** [jmcnamara/excel-writer-xlsx#120]
Hi All,

Please, Help me with your suggestions. I am having trouble in uploading an excel file into MS SharePoint.
 
While i am trying to upload an Excel file into MS SharePoint using Perl script.. I am getting the following Error.

Couldn't open https://one.mysite.net/sites/Fin/Shared Documents/Fin Projects/Project Reports: Unauthorized.
Wont put unless I can lock for 10 minutes

With Browser i am able to login and view [ also upload and download ] the files from the Sharepoint site.

This is my code:

```perl
use HTTP::DAV;

   $d = new HTTP::DAV;
    $url = "https://one.mysite.net/sites/Fin/Shared Documents/Fin Projects/Project Reports";
   $d->credentials( -user=>"My_User_ID",-pass =>"123456789_pwd", 
                    -url =>$url,      -realm=>"DAV Realm" );

   if ( $d->open( -url=> $url ) ) 
   {
   print "successfully logged in";
   }
   else
   {
      print "Couldn't open $url: " .$d->message . "\n";
	}
   # Make a null lock on newdir
   $d->lock( -url => "$url", -timeout => "10m" ) 
       or die "Wont put unless I can lock for 10 minutes\n";

   # Upload multiple files to newdir.
    if ( $d->put( -local => "C:\Users\My Desktop\MY_XLSX_FILE.xlsx", -url => $url ) ) {
       print "successfully uploaded multiple files to $url\n";
    } else {
      print "put failed: " . $d->message . "\n";
    }

   $d->unlock( -url => $url );
``

Thanks in Advance!

Gayathri T

**Comment by jmcnamara** [comment]
Hi,

This is the issue tracker for Excel::Writer::XLSX. 

It isn't a good place for asking general questions. Especially questions that may be related to Sharepoint or Web DAV.

StackOverflow is a better place to ask questions like this.

Regards,

John
