### ISSUE TITLE
Feature request: Workbook get_worksheet() method

### ISSUE THREAD

**Issue by Ctesias** [jmcnamara/excel-writer-xlsx#124]
For big multisheet workbooks it would be helpful to be able to get a worksheet by name.  It  would allow for cleaner code when trying to put a lot of information in different sheets if I can refer to them by name instead of order-based location in the workbook, and much more concise then having to loop through all the sheets to find the one I want:

    my $worksheet  = $workbook->get_worksheet($name);

I write methods to do this for me in my excel object projects 100% of the time.  I think enough that it would be helpful to incorporate directly

**Comment by jmcnamara** [comment]
Hi Derek,

That is a reasonable suggestion but overall I'm not in favour of adding features that can be handled in the end user program unless there are a lot of requests for it. And in this case there hasn't been very many.

The same effect, as you probably know since you said that you have functions for it, can be achieved with a hash lookup:

```perl
#!/usr/bin/perl

use strict;
use warnings;
use Excel::Writer::XLSX;

my $workbook = Excel::Writer::XLSX->new( 'test.xlsx' );

my $worksheet1 = $workbook->add_worksheet( 'Foo' );
my $worksheet2 = $workbook->add_worksheet( 'Bar' );

# Store the worksheet references by name.
my %worksheets;
for my $worksheet ( $workbook->sheets() ) {
    $worksheets{ $worksheet->get_name() } = $worksheet;
}

# Now look up a worksheet.
my $worksheet = $worksheets{'Foo'};

$worksheet->write( 0, 0, "Hi Excel!" );

$workbook->close();

```

I'll leave the feature request open for a few months. If it gathers some +1s I'll consider adding it.

John

**Comment by Ctesias** [comment]
If I offer to do a pull request and write it myself, are you open to that?

**Comment by jmcnamara** [comment]
> If I offer to do a pull request and write it myself, are you open to that

No. The issue isn't the code.

It is just that, as I said above, I'm not in favour of adding features that can be handled in Perl unless there is a lot of interest in it. That generally indicates a deficiency in the API. The `write_row()` function was a case in point.

If there is reasonable interest in this feature I'll add it as well.

John

**Comment by jmcnamara** [comment]
I eventually got a number of requests for this so I added a `get_worksheet_by_name()` method in Excel::Writer::XLSX version 0.90.

Thanks for the prompt.
