### ISSUE TITLE
Feature request: Workbook set_black_and_white() method

### ISSUE THREAD

**Issue by bokutin** [jmcnamara/excel-writer-xlsx#125]
Hello.

Complex Xlsx also I was able to create.
It is thanks to this module.
Thanks you.

I did not have black-and-white printing.
I want to output as follows.

    <pageSetup blackAndWhite="1" />

Directly edit the lib/Excel/Writer/XLSX/Worksheet.pm:_write_page_setup(), we were able to do.

One There is hope. Is it possible to have them add the following method.
Worksheet: set_black_and_white

Although the following variables are available, it appears not to have been used for output..

    $self->{_black_white}

Please consider.

**Comment by jmcnamara** [comment]
Hi,

Thanks for the suggestion. I've added it on master and it should find its way into the next release: The API is:

```perl
$worksheet->print_black_and_white();
```

Regards,

John

**Comment by bokutin** [comment]
Thank you for the quick response!

In an environment that was making the Excel file, I have tested the master branch.
It was confirmed that it has been successfully output.

Awesome!

**Comment by jmcnamara** [comment]
Fixed in version 0.84. Forgot to close this issues. Closing now.
