### ISSUE TITLE
Targeting specific versions of Microsoft Excel File Formats

### ISSUE THREAD

**Issue by msmcgillis** [jmcnamara/excel-writer-xlsx#126]
I'm not sure this is really a bug against Excel::Writer::XLSX but it is an issue that you might want to think about.

XLSX has a standard that defines how things should be however for various reasons different version of Microsoft Excel produce different file contents either from bugs or by design or based on different defaults.

If I use Excel::Writer::XLSX to generate a XLSX file I believe you have targeted file formats that are consistent with a specific version of Excel and not necessarily consistent with the XLSX specification.

The net impact of all this is for example right now if you attempt to open a file generated by Excel::Writer::XLSX that includes a chart with a title in LibreOffice the title does not appear.

LibreOffice is aware of this issue as https://bugs.documentfoundation.org/show_bug.cgi?id=82216 but I thought I would bring this up so you are aware.

Feel free to close this if you don't see it as anything for Excel::Writer::XLSX to resolve/address.

**Comment by jmcnamara** [comment]
Hi @msmcgillis,

Thanks for the report.

Excel::Writer::Xlsx is 100% consistent with the Excel 2007 file format and there are hundreds of test cases in the test suite that compare generated files against Excel files byte for byte (more of less). 

If Excel 2007 isn't consistent with its own specification or LibreOffice then those things are outside of my control.

Sorry,

John
