### ISSUE TITLE
Feature request: insert_chart() size and placement option

### ISSUE THREAD

**Issue by ale275** [jmcnamara/excel-writer-xlsx#128]
Hallo 

I've a feature request for the insert_chart() function. I'd like to modify the default behaviour of placing and size using a parameter.

Now the setting is
![chart_default](https://cloud.githubusercontent.com/assets/405331/7369017/5ffae5e2-edae-11e4-8854-a57af78f4aa2.PNG)
I'd like to set it to 
![chart_option](https://cloud.githubusercontent.com/assets/405331/7369021/67e9db46-edae-11e4-9170-6b566f5cfbc3.PNG)
Regards
Ale

**Comment by jmcnamara** [comment]
Fixed on master. You can now do:

    $worksheet->insert_image( 'A1', 'perl.png', { object_position => 1 } );
