### ISSUE TITLE
utf8 character translated.

### ISSUE THREAD

**Issue by msmcgillis** [jmcnamara/excel-writer-xlsx#129]
This code:

```perl
#!/usr/bin/perl
use Excel::Writer::XLSX;
print $Excel::Writer::XLSX::VERSION."\n";
my $workbook=Excel::Writer::XLSX->new('test.xlsx');
my $worksheet=$workbook->add_worksheet();
my $string='GRUPO EMPRESARIAL SAN JOSÉ';
$worksheet->write(0,0,$string);
```

The generated excel file string in cell 0,0 is getting translated to:

GRUPO EMPRESARIAL SAN JOSÃ

from what I can tell from the documentation utf8 strings should be safe to use? which is what is in $string.

**Comment by jmcnamara** [comment]
Try adding `use utf8;` to the file so that perl knows that it is UTF-8.

**Comment by jmcnamara** [comment]
Sorry for previous terse reply it was from my phone.

I tested the suggested fix and it works:

```perl

#!/usr/bin/perl

use Excel::Writer::XLSX;
use utf8;

my $workbook=Excel::Writer::XLSX->new('test.xlsx');
my $worksheet=$workbook->add_worksheet();
my $string='GRUPO EMPRESARIAL SAN JOSÉ';
$worksheet->write(0,0,$string);
```
Output:

![screenshot](https://cloud.githubusercontent.com/assets/94267/7427730/bafa24d0-efd9-11e4-9ef5-a27fd65cccf7.png)

**Comment by msmcgillis** [comment]
Thanks!

Works for me as well.

**Comment by jmcnamara** [comment]
Thanks for letting me know. Closing.
