### ISSUE TITLE
Question: Color Palette Dropdown configurable? 

### ISSUE THREAD

**Issue by mcmillhj** [jmcnamara/excel-writer-xlsx#130]
I have read through the [`COLOURS-IN-EXCEL`](https://metacpan.org/pod/Excel::Writer::XLSX#COLOURS-IN-EXCEL) section of the documentation and the `colors.pl` example file for adding custom colors to the workbook and we have been using set_custom_color to format cell color for some time in our reports. 

We now have a request that the reports have a custom dropdown color palette to match the standard company color palette, after playing around for a little while I can't seem to modify that dropdown at all using set_custom_color. Is there a way to modify this dropdown with Excel::Writer::XLSX or is this the expected behavior? 

Either way is fine, I am just interested to know if this is possible.

**Comment by jmcnamara** [comment]
Custom colours isn't what you need here. They are mainly for backward compatibility with Spreadsheet::WriteExcel and aren't very useful in Excel::Writer::XLSX where you can now use Html style `#rrggbb` colour codes instead.

What you are looking for is controlled by the workbook "theme" which isn't currently configurable in Excel::Writer::XLSX. You may (or may not) be able to replace the default theme in the module or the output files with the one you need. However, this may affect image and worksheet object sizing if the theme changes the default font sizes.

John

**Comment by mcmillhj** [comment]
Ok, thanks for the quick feedback. We have a workaround that is a little ugly but seems to work every time, at least in our environment that I'd be happy to share. It involves unzipping the THMX file and the XLSX workbook and copying an XML file from the THMX folder to the XLSX file to apply the custom theme.

**Comment by jmcnamara** [comment]
I'm glad you found a workaround.

It is a planned feature, in the medium term, to add support via the API for adding theme.xml files.

John.
