### ISSUE TITLE
Feature request: Chart Data Label Orientation

### ISSUE THREAD

**Issue by jvera888** [jmcnamara/excel-writer-xlsx#131]
Is there a way to change data label orientations in charts?  I noticed what appeared to be an option to do this for cell formatting, but it would be really useful to have in charts.  I thought of formatting a cloned set of cells to use in the charts, although I haven't tried it yet, but that seems like it would be an ugly work-around even if it worked.
Thanks for your help!
Cheers,
Cris

**Comment by jmcnamara** [comment]
> Is there a way to change data label orientations in charts

Not currently. I'll mark this as a feature request.

John

**Comment by jmcnamara** [comment]
This feature is now available via the font property of data labels:

```perl
    $chart->add_series(
        values      => '=Sheet1!$A$1:$A$5',
        data_labels => {
            value => 1,
            font  => { rotation => 45 }
        },
    );

```
