### ISSUE TITLE
Blank Cells on iPhone E-mail with set_optimization

### ISSUE THREAD

**Issue by DanRagle** [jmcnamara/excel-writer-xlsx#132]
Probably not your issue, but asking in case you or someone in the community has a work around. 

When creating .xlsx spreadsheets with Excel::Writer::XLSX **and** using set_optimization, the text spreadsheet cells, when viewed from an iPhone E-mail, are blank or non-existent. 

```
use strict;
use warnings;
use Excel::Writer::XLSX ();

my $filename  = 'reload.xlsx';
my $workbook  = Excel::Writer::XLSX->new($filename);
$workbook->set_optimization();

my $centermerge = $workbook->add_format(
    align => 'center',
);

my $worksheet = $workbook->add_worksheet();

$worksheet->merge_range(0, 0, 0, 2, 'Centered Text', $centermerge);

$worksheet->write(1, 0, 'Hi Excel!');
$worksheet->write(1, 1, 'Column B');
$worksheet->write(1, 2, 21);

$workbook->close();
```

When viewed from the iPhone E-mail app I see a blank three column cell in the first row, and the first two columns of the second row are also blank. The **21** alone appears as expected. And if I make the **21** some other text, then only a single blank cell is displayed on the iPhone (only one row and no second or third column). Removing the "set_optimization" fixes the problem. I also tried the test without the merge row entirely (where there was only one row with **Hi Excel!**, **Column B**, etc.) with the same results.

My test system is as follows:

```
Perl version   : 5.010001
OS name        : linux
Module versions: (not all are required)
                 Excel::Writer::XLSX     	0.84
                 Spreadsheet::WriteExcel 	2.37
                 Archive::Zip            	1.30
                 XML::Writer             	0.606
                 IO::File                	1.14
                 File::Temp              	0.22
```

Thank you!

**Comment by jmcnamara** [comment]
I thought that this was documented but apparently it isn't.

In `set_optimization()` mode strings aren’t stored in usual Excel structure call “shared strings” and instead are written “in-line”. This is a speed and memory optimisation.

This is a documented Excel feature that is supported by most spreadsheet applications. One known exception is Apple Numbers for Mac where the string data isn’t displayed. The iPhone app is probably the same.

There isn't any workaround apart from not using `set_optimization()`.

John

**Comment by DanRagle** [comment]
Ok, thank you.
