### ISSUE TITLE
set_column()

### ISSUE THREAD

**Issue by whichen** [jmcnamara/excel-writer-xlsx#134]
the $format is defined.
when I use :  $worksheet->set_column('A:C', 20 ,$format1)
the notes will appear "Redundant argument in sprintf at .../Excel/Writer/XLSX/Pachage/Style.pm"
when I removed the $format1, the problem will disappear.
Who can tell me the reason?
Thanks

**Comment by jmcnamara** [comment]
Hi,

Could you post a small, complete, working example that demonstrates the issue. 

Thanks,

John

**Comment by whichen** [comment]
Hi,

When I run this script, the warning is below:
[cid:image001.png@01D0CE9D.AFDC44A0]

After removing the $fm1, the problem will disappear.

$worksheet->set_column('A:C',20,$fm1);

Thanks.
White

**Comment by jmcnamara** [comment]
Hi,

> When I run this script, the warning is below:

What script? If you attached a script via email then please note that GitHub doesn't accept attachments.

Please add the sample program here: #134

In order to save time, make sure that it is small, complete and working.

Thanks,

John

**Comment by whichen** [comment]
#!/users/whichen/perl/bin/perl5.22.0 


#use Spreadsheet::ParseExcel;
#use Spreadsheet::ParseExcel::FmtUnicode;
#use Spreadsheet::WriteExcel;
use Excel::Writer::XLSX;

my $workbook =Excel::Writer::XLSX->new('test.xlsx');
my $worksheet=$workbook->add_worksheet('test1');
my %fond=(
	font=>'Calibri',
	size=>12,
	color=>'blue',
	bold=>1,
	align=>'center',
	border=>1
);
my $fm1=$workbook->add_format(%fond);

my $fm_head=$workbook->add_format(
	border=>6,
	valign=>'vcenter',
	align=>'center',
	size=>12,
	color=>'blue',
	bold=>1,
);
#$worksheet->merge_range('A1:C3','Hello Excel!',$fm_head);
$worksheet->set_column('A:C',20,$fm1);
$worksheet->set_row(0,20);
$worksheet->write(0,0,'Hello Excel!');

**Comment by jmcnamara** [comment]
Hi,

That is a new warning introduced in Perl 5.22: http://perldoc.perl.org/perldelta.html#New-Diagnostics

I've push a fix for it to  the master branch and there is a new version on the way to CPAN.

Thanks for the report.

John
