### ISSUE TITLE
Bug: Excel error while use ROUND formula 

### ISSUE THREAD

**Issue by DimonON** [jmcnamara/excel-writer-xlsx#137]
There's an excel error while opening a workbook which created with ROUND formula.

``` perl
#!/usr/bin/perl 
use strict; 
use warnings;
use Excel::Writer::XLSX;

my $workbook  = Excel::Writer::XLSX->new( 'example.xlsx' );
my $worksheet = $workbook->add_worksheet();

#my $formula = '=ROUND(1000.12345;2)';
#$worksheet->write_formula( 0, 0, $formula);
$worksheet->write( 0, 0, '=ROUND(1000.12345;2)' );

$workbook->close;
```

**Comment by jmcnamara** [comment]
Hi,

From the [docs](https://metacpan.org/pod/Excel::Writer::XLSX#FORMULAS-AND-FUNCTIONS-IN-EXCEL):

> The range and comma operators can have different symbols in non-English versions of Excel. These may be supported in a later version of Excel::Writer::XLSX. In the meantime European users of Excel take note:

```perl
$worksheet->write('A1', '=SUM(1; 2; 3)'); # Wrong!!
$worksheet->write('A1', '=SUM(1, 2, 3)'); # Okay
```

So if you make the the following change to your program it should work:

```perl
$worksheet->write( 0, 0, '=ROUND(1000.12345;2)' );
```

John

**Comment by DimonON** [comment]
Hi,
Thank you ) This way it works fine.
Sorry for my inattention
