### ISSUE TITLE
Conditional formatting "stop if true" feature

### ISSUE THREAD

**Issue by f20** [jmcnamara/excel-writer-xlsx#138]
Excel::Writer::XLSX does not currently support the "stop if true" feature of conditional formatting in Microsoft Excel.  When "stop if true" is set on a conditional formatting rule, for any cell that meets that rule, subsequent rules are not examined.  This feature can simply the expression of conditional formatting rules.

**Comment by jmcnamara** [comment]
Thanks for that. I make some comments inline in the PR.

**Comment by jmcnamara** [comment]
Closed in version 0.86 on CPAN.

Thanks.
