### ISSUE TITLE
write_string issues warnings if called with undef

### ISSUE THREAD

**Issue by ft-lie** [jmcnamara/excel-writer-xlsx#142]
Calling write_string with undef issues a warning.

Suggests either updating the documentation that write_string do require a string, and include in the example e.g. "...if defined $text;"

Or modifying row 2232 to include 

```
my $str = $_[2] || '';
.               ______
```

Or add a row:

```
return unless defined $str;
```

(BTW: in the read-first example addworksheet should be add_worksheet, unless that was an exercise for the issuer to solve ;-) )

```
#warning-generating example
use strict;
use Excel::Writer::XLSX;
my $xls_string;
open my $fh, '>', \$xls_string or die "Failed to open filehandle: $!";
require Excel::Writer::XLSX;  
my $workbook = Excel::Writer::XLSX->new($fh);
my $worksheet = $workbook->add_worksheet();

$worksheet->write_utf16be_string(0, 0, undef);
$worksheet->write_string(0, 0, undef);
```

**Comment by jmcnamara** [comment]
> Suggests either updating the documentation that write_string do require a string, and include in the example e.g. "...if defined $text;"

Thanks for the suggestion.



> BTW: in the read-first example addworksheet should be add_worksheet, unless that was an exercise for the issuer to solve

Fixed. Thanks.
