### ISSUE TITLE
Use of uninitialized value in numeric eq (==)

### ISSUE THREAD

**Issue by NicoHood** [jmcnamara/excel-writer-xlsx#147]
The error:
```
./test2.pl param
Use of uninitialized value in numeric eq (==) at /usr/lib/perl5/site_perl/5.10.0/Excel/Writer/XLSX/Workbook.pm line 932 during global destruction.
        (in cleanup) Can't use an undefined value as an ARRAY reference at /usr/lib/perl5/site_perl/5.10.0/Excel/Writer/XLSX/Workbook.pm line 1536 during global destruction.
```

The script:
```perl
#!/usr/bin/perl

use strict;
use warnings;

use Excel::Writer::XLSX;

die "Usage: $0 [FILE...]\n" if $#ARGV < 0;

my $myconfig_file = 'textdoesntmatter';
my $myrowOffset = 1;
my $mycolOffset = 1;

my $workbook = Excel::Writer::XLSX->new( 'perl_output.xlsx' );
addToSheet();

sub addToSheet {
	my $worksheet2xx = $workbook->add_worksheet();
	return;
}
```

If I add `$workbook->close();` the script works again. Is this behavior intended?
If I remove one of the variables of the param check the error is also gone which is very weird.

Is this just because I used perl wrong or because there is a bug? I guess its the first.

**Comment by jmcnamara** [comment]
It is a documented feature due to Perl variable scope and the garbage collector. 

See the documentation for ` close()`.

**Comment by NicoHood** [comment]
Does it make sense to put it inside `END {...}` in the case the program crashes?

**Comment by jmcnamara** [comment]
I don't know.

**Comment by NicoHood** [comment]
Yes it does. then the program dies without and excel error.
