### ISSUE TITLE
Multiple Lines In Table Header

### ISSUE THREAD

**Issue by wreade** [jmcnamara/excel-writer-xlsx#148]
Hello,

I'm attempting to make my spreadsheet have thinner columns and a taller header row. Within the header row, I need the header text to wrap so that it can be read by the user. I know that I can't use formatting in the table header row, but I can't use line breaks (e.g., "\n") either. I get the following message when I do that.

"Excel found unreadable content in 'spreadsheet.xlsx'. Do you want to recover the contents of this workbook? If you trust the source of this workbook, click Yes."

When I click yes, Excel tells me that it was able to open the file by repairing or removing the unreadable content. When I look at the header row, I see the header text in each column, but the new lines aren't being read. If I enter each cell and hit the enter key to leave the cell, Excel then reads the new line characters and displays the header text as I hoped.

Any thoughts on this?

Thanks!

Will

**Comment by jmcnamara** [comment]
Hi,

I've added a fix for the "\n" issues and also the option to add formatting for the header in a column to the GitHub master.

Here is an example:

```perl
#!/usr/bin/perl

use warnings;
use strict;
use Excel::Writer::XLSX;

my $workbook  = Excel::Writer::XLSX->new( 'table.xlsx' );
my $worksheet = $workbook->add_worksheet();
my $text_wrap = $workbook->add_format( text_wrap => 1, xf_index => 1 );

$worksheet->set_column('C:F', 10.288);
$worksheet->set_row(2, 30);

# Add the table.
$worksheet->add_table(
    'C3:F13',
    {
        columns => [
            {},
            {},
            {},
            { header => "Column\n4", header_format => $text_wrap },
        ]
    }
);

$workbook->close();

```

And the output:

![screenshot](https://github-cloud.s3.amazonaws.com/assets/94267/10565523/3ec717a2-75ca-11e5-95b4-a08b36bf1966.png)

**Comment by jmcnamara** [comment]
Closed in version 0.86 on CPAN.

Thanks.

**Comment by wreade** [comment]
Thanks for the fast response! I will check it out.

**Comment by wreade** [comment]
That worked perfectly! Thanks!
