### ISSUE TITLE
Feature request: Format cells without writing new data

### ISSUE THREAD

**Issue by NicoHood** [jmcnamara/excel-writer-xlsx#149]
Hi,
I want to format some cells individual (red, blue, green) and then add a border color around the colored cells. Is there an easy way to add a format around a range afterwards? Similar to the merging function, without merging the cells.

I have no change to fiddle the border inside while writing the colors. That'd make my program very complex (its a bit more than just colors).

(Btw thx for the table header format addition, works great!)

**Comment by jmcnamara** [comment]
> Is there an easy way to add a format around a range afterwards?

Unfortunately, no. It was/is a planned feature, and I put some of the internal structure in place, but I didn't get time to implement it.

The [Spreadsheet::WriteExcel::Styler](http://search.cpan.org/~dami/Spreadsheet-WriteExcel-Styler/lib/Spreadsheet/WriteExcel/Styler.pm) module does something like what you are looking for. It also works with Excel::Writer::XLSX, despite the name.

**Comment by NicoHood** [comment]
Too bad. You could mark it as feature request though.
Thx for the advice, I'll have a look.

**Comment by jmcnamara** [comment]
> You could mark it as feature request though.
Done.

**Comment by jmcnamara** [comment]
Closed as "won't fix" since I'm never going to get time to work on this.
