### ISSUE TITLE
Fails to create secondary x-axis

### ISSUE THREAD

**Issue by matajaz** [jmcnamara/excel-writer-xlsx#152]
Hi,

I am struggeling with creating a secondary x-axis in my charts.

$$chartref{$$hashref{$counter}{SHEET}}->set_title ( name => "$counter" );
$$chartref{$$hashref{$counter}{SHEET}}->set_x_axis( name => 'Time1', visible => 1 )
$$chartref{$$hashref{$counter}{SHEET}}->set_x2_axis( name => 'Time2', visible => 1 );
$$chartref{$$hashref{$counter}{SHEET}}->set_y_axis( name => 'Number' );
$$chartref{$$hashref{$counter}{SHEET}}->set_plotarea( pattern => 'solid' );
$$chartref{$$hashref{$counter}{SHEET}}->set_plotarea( weight => 'hairline' );

First x-axis is working fine and I can add two time series in the chart.
I see two series in the same chart but I do not see the seconday x-axis.

Is there any working example where you create a graph with 2 x-axis and 2 series?

Br Mathias

**Comment by jmcnamara** [comment]
> Is there any working example where you create a graph with 2 x-axis and 2 series?

Yes. There is an example in the [Chart documentation](http://search.cpan.org/~jmcnamara/Excel-Writer-XLSX/lib/Excel/Writer/XLSX/Chart.pm#Secondary_Axes) and in the examples: [chart_secondary_axis.pl](http://search.cpan.org/~jmcnamara/Excel-Writer-XLSX/lib/Excel/Writer/XLSX/Examples.pm#Example:_chart_secondary_axis.pl) and [chart_combined.pl](http://search.cpan.org/~jmcnamara/Excel-Writer-XLSX/lib/Excel/Writer/XLSX/Examples.pm#Example:_chart_combined.pl).

**Comment by matajaz** [comment]
Tanks for your Quick reply John.
I can only find an example of 2 y-axis not 2 x-axis.

I searched for set_x2 in The example but could not find a match.

Br
Mathias
Den 23 okt 2015 2:10 em skrev "John McNamara" <notifications@github.com>:

**Comment by jmcnamara** [comment]
Could you show an example of the type of chart you want to create.

**Comment by matajaz** [comment]
Hi John

I do tests and during the test I change parameters and would like to
compare measurements before and after change.
Using one set of parameters the first period and another set of parameters
the second period

Today I have one chart with one x-axis showing time and y-axis showing
measurement results.
Instead of showing one graph over the entire period I would like to cut the
period into two halfes.
It would be nice to present this with a graph having two x-axis.
One for each period.

I copied an example from the web.
[image: Inline image 1]


http://superuser.com/questions/188064/excel-chart-with-two-x-axes-horizontal-possible

<http://superuser.com/questions/188064/excel-chart-with-two-x-axes-horizontal-possible>

<http://superuser.com/questions/188064/excel-chart-with-two-x-axes-horizontal-possible>
T
<http://superuser.com/questions/188064/excel-chart-with-two-x-axes-horizontal-possible>his
graph is not showing time on x-axis but that is not important.

If it is not possible to make a graph with two x-axis I wonder if it is
possible to insert a vertical line on a specific place in the graph?
In my case I would like to insert the line in the middle of my graph which
indicates where I have done the change.

B
<http://superuser.com/questions/188064/excel-chart-with-two-x-axes-horizontal-possible>r
Mathias

**Comment by matajaz** [comment]
Hi John,

I am sorry to disturb you.

Here is a better example of what kind of graph I want to create made from
my own data.

[image: Inline image 1]

Is it possible to generate a graph like this with Excel::Writer?

Kind regards
Mathias

**Comment by jmcnamara** [comment]
> [image: Inline image 1]
>
> Is it possible to generate a graph like this with Excel::Writer?

Github doesn't support images in email replies. Can you post the image via the website.

**Comment by matajaz** [comment]
Oooh, I am sorry about that.
I did not notice it did not look well on the web page.

The graph looks like this:
![image](https://cloud.githubusercontent.com/assets/4008385/10768950/ec813254-7ce3-11e5-9d6d-f4e6dd328988.png)


One x-axis with time on the top of the graph and one time period below the graph.

Br Mathias

**Comment by jmcnamara** [comment]
That should be possible although the exact parameters are tricky to get right.

Here is a small working example:

```perl
#!/usr/bin/perl

use warnings;
use strict;
use Excel::Writer::XLSX;

my $workbook  = Excel::Writer::XLSX->new( 'second.xlsx' );
my $worksheet = $workbook->add_worksheet();
my $chart     = $workbook->add_chart( type => 'line', embedded => 1 );


my $data = [
    [ 1,  2,  3,  4,  5  ],
    [ 8,  7,  6,  3,  2  ],
    [ -1, -2, -3, -4, -5 ],
    [ 2,  3,  6,  7,  8  ],
];

$worksheet->write( 'A1', $data );

$chart->add_series(
    categories => '=Sheet1!$A$1:$A$5',
    values     => '=Sheet1!$B$1:$B$5',
);

$chart->add_series(
    categories => '=Sheet1!$C$1:$C$5',
    values     => '=Sheet1!$D$1:$D$5',
    y2_axis    => 1,
);

# Set the axes properties.
$chart->set_x_axis( name => 'Axis 1' );

$chart->set_x2_axis(
    name           => 'Axis 2',
    label_position => 'next_to',
    visible        => 1,
);

$chart->set_y2_axis(
    crossing => 'max',
    visible  => 0
);

$worksheet->insert_chart( 'E9', $chart );

$workbook->close();
```
Output:

![screenshot](https://cloud.githubusercontent.com/assets/94267/10775422/18e26ec8-7d00-11e5-9c2f-8efb1e132115.png)

If you have any followup questions please post a small similar working example.

**Comment by matajaz** [comment]
Many thanks John,

It is working perfectly.

Br Mathias

**Comment by jmcnamara** [comment]
Thanks for the followup. Closing.
