### ISSUE TITLE
Secondary axis missing bold font for combined chart

### ISSUE THREAD

**Issue by rdboisvert** [jmcnamara/excel-writer-xlsx#154]
I found a bug related to the secondary Y axis and combined charts.  If I use the example of the "Combine chart - secondary Y axis" provided with the Chart documentation (http://search.cpan.org/~jmcnamara/Excel-Writer-XLSX-0.86/lib/Excel/Writer/XLSX/Chart.pm#Combined_Charts) and change the `set_y_axis ()` and `set_y2_axis ()` functions to include a bold font, then only the primary Y axis is bold. This problem does not occur if not using a combined chart.

    $column_chart->set_y_axis( name => 'Sample length (mm)', num_font => {bold => 1} );
    $column_chart->set_y2_axis( name => 'Target length (mm)', num_font => {bold => 1} );

**Comment by jmcnamara** [comment]
Hi,

Could you post a small example program that demonstrates the issue: https://github.com/jmcnamara/excel-writer-xlsx/blob/master/CONTRIBUTING.md

Thanks,

John

**Comment by rdboisvert** [comment]
Using your example from (http://search.cpan.org/~jmcnamara/Excel-Writer-XLSX-0.86/lib/Excel/Writer/XLSX/Chart.pm#Combined_Charts) I made the adjustments in **bold**.

    use strict;
    use warnings;
    use Excel::Writer::XLSX;

    my $workbook  = Excel::Writer::XLSX->new( 'chart_combined.xlsx' );
    my $worksheet = $workbook->add_worksheet();
    my $bold      = $workbook->add_format( bold => 1 );

    # Add the worksheet data that the charts will refer to.
    my $headings = [ 'Number', 'Batch 1', 'Batch 2' ];
    my $data = [
        [ 2,  3,  4,  5,  6,  7 ],
        [ 10, 40, 50, 20, 10, 50 ],
        [ 30, 60, 70, 50, 40, 30 ],

    ];

    $worksheet->write( 'A1', $headings, $bold );
    $worksheet->write( 'A2', $data );

    #
    # In the first example we will create a combined column and line chart.
    # They will share the same X and Y axes.
    #

    # Create a new column chart. This will use this as the primary chart.
    my $column_chart = $workbook->add_chart( type => 'column', embedded => 1 );

    # Configure the data series for the primary chart.
    $column_chart->add_series(
        name       => '=Sheet1!$B$1',
        categories => '=Sheet1!$A$2:$A$7',
        values     => '=Sheet1!$B$2:$B$7',
    );

    # Create a new column chart. This will use this as the secondary chart.
    my $line_chart = $workbook->add_chart( type => 'line', embedded => 1 );

    # Configure the data series for the secondary chart.
    $line_chart->add_series(
        name       => '=Sheet1!$C$1',
        categories => '=Sheet1!$A$2:$A$7',
        values     => '=Sheet1!$C$2:$C$7',
        y2_axis    => 1,
    );

    # Combine the charts.
    $column_chart->combine( $line_chart );

    # Add a chart title and some axis labels. Note, this is done via the
    # primary chart.
    $column_chart->set_title( name => 'Combined chart - same Y axis' );
    $column_chart->set_x_axis( name => 'Test number' );
$column_chart->set_y_axis( name => 'Sample length (mm)'**, num_font => {bold => 1}** );
$column_chart->set_y2_axis( name => 'Target length (mm)'**, num_font => {bold => 1}** );

    # Insert the chart into the worksheet
    $worksheet->insert_chart( 'E2', $column_chart );

**Comment by jmcnamara** [comment]
Hi,

The example in the repo is incorrect here. The `y2` properties in a combined chart apply to the secondary chart. So if you change your example to the following it should work as expected:

```perl
    $column_chart->set_y_axis( name => 'Sample length (mm)', num_font => {bold => 1} );
    $line_chart->set_y2_axis( name => 'Target length (mm)', num_font => {bold => 1} );
```

I'll update the docs and the example.

**Comment by rdboisvert** [comment]
You're right, my example was wrong.  However, the correction doesn't fix it.

**Comment by jmcnamara** [comment]
> However, the correction doesn't fix it.

Are you sure?

I ran this version of your program:

```perl

use strict;
use warnings;
use Excel::Writer::XLSX;

print Excel::Writer::XLSX->VERSION, "\n";


my $workbook  = Excel::Writer::XLSX->new( 'chart_bold.xlsx' );
my $worksheet = $workbook->add_worksheet();
my $bold      = $workbook->add_format( bold => 1 );

# Add the worksheet data that the charts will refer to.
my $headings = [ 'Number', 'Batch 1', 'Batch 2' ];
my $data = [
    [ 2,  3,  4,  5,  6,  7 ],
    [ 10, 40, 50, 20, 10, 50 ],
    [ 30, 60, 70, 50, 40, 30 ],

];

$worksheet->write( 'A1', $headings, $bold );
$worksheet->write( 'A2', $data );

# Create a new column chart. This will use this as the primary chart.
my $column_chart = $workbook->add_chart( type => 'column', embedded => 1 );

# Configure the data series for the primary chart.
$column_chart->add_series(
    name       => '=Sheet1!$B$1',
    categories => '=Sheet1!$A$2:$A$7',
    values     => '=Sheet1!$B$2:$B$7',
);

# Create a new column chart. This will use this as the secondary chart.
my $line_chart = $workbook->add_chart( type => 'line', embedded => 1 );

# Configure the data series for the secondary chart.
$line_chart->add_series(
    name       => '=Sheet1!$C$1',
    categories => '=Sheet1!$A$2:$A$7',
    values     => '=Sheet1!$C$2:$C$7',
    y2_axis    => 1,
);

# Combine the charts.
$column_chart->combine( $line_chart );

# Add a chart title and some axis labels. Note, this is done via the
# primary chart.
$column_chart->set_title( name => 'Combined chart - Bold Axes' );
$column_chart->set_x_axis( name => 'Test number' );

# Bold added.
$column_chart->set_y_axis( name => 'Sample length (mm)', num_font => {bold => 1} );
$line_chart->set_y2_axis( name => 'Target length (mm)', num_font => {bold => 1} );

# Insert the chart into the worksheet
$worksheet->insert_chart( 'E2', $column_chart );

$workbook->close();

```

And got this output:

![screenshot](https://cloud.githubusercontent.com/assets/94267/12180369/0b5ecc4a-b574-11e5-8555-598b12fc9a09.png)

Both y axes are bold. That is the issue that you are reporting, right?

With Excel::Writer::XLSX 0.86 and Excel 2007, 2011 and 2013.

**Comment by rdboisvert** [comment]
No, that doesn't work.  I'm using Excel 2013 on Win7.  When I open the file it is not bold.  If I change, save and reopen it is bold.

**Comment by jmcnamara** [comment]
Try the following:

```perl
$column_chart->set_y_axis(
    name     => 'Sample length (mm)',
    num_font => { bold => 1, baseline => -1 }
);

$line_chart->set_y2_axis(
    name     => 'Target length (mm)',
    num_font => { bold => 1, baseline => -1 }
);

```

**Comment by rdboisvert** [comment]
Yes, that change worked.

**Comment by rdboisvert** [comment]
Glad it worked, but not sure why.  Is there something wrong with using `num_font => { bold => 1 }` instead of `num_font => { bold => 1, baseline => -1 }`?

**Comment by jmcnamara** [comment]
> Glad it worked, but not sure why.

I'm not fully sure why it is required either. The `baseline` property isn't available via the Excel UI but it has something to do with allowing enough space for the bold font to be displayed.

In general it isn't required. Perhaps in this particular case the space available to the axes isn't sufficient to display bold. If you manually make the axis box bigger (in the original example) do you see the bold font then? Also (again in the original) if you select the text in the axis is the Bold icon highlighted?

I'm also not sure why it worked for me and not for you. What language version of Excel are you using? Also, what version of Excel::Writer::XLSX are you using?

**Comment by rdboisvert** [comment]
It appears the error was in my code.  I was using `$line_chart->set_y_axis()` instead of `$column_chart->set_y_axis()`.  `baseline` made no difference in this case.

As always, thanks for your help.
