### ISSUE TITLE
Feature request: tick mark positions

### ISSUE THREAD

**Issue by wang-q** [jmcnamara/excel-writer-xlsx#155]
Hi,

I want to place tick marks inside plotarea, like red circle in the attached screen shot. By default Excel::Writer::XLSX::Chart places tick marks outside, indicated by purple circle.

In VBA, it can be set by the following codes.

```vba
myChart.Axes(xlCategory).MajorTickMark = xlTickMarkInside
```

![screen shot 2016-01-13 at 12 32 40](https://cloud.githubusercontent.com/assets/6592693/12285145/16289746-b9f2-11e5-8185-429dfad8147a.png)

(Thanks for your great working on this awesome module!)

**Comment by jmcnamara** [comment]
Seems reasonable. I'll try to add it in the next release.

**Comment by jmcnamara** [comment]
In the meantime you can workaround it by accessing the underlying axis object directly:

```perl
#!/usr/bin/perl

use strict;
use warnings;
use Excel::Writer::XLSX;

my $workbook  = Excel::Writer::XLSX->new( 'chart_tick.xlsx' );
my $worksheet = $workbook->add_worksheet();

my $data = [
    [ 2,  3,  4,  5,  6,  7 ],
    [ 10, 40, 50, 20, 10, 50 ],
];

$worksheet->write( 'A2', $data );

my $chart = $workbook->add_chart( type => 'column', embedded => 1 );

$chart->add_series(
    name       => '=Sheet1!$B$1',
    categories => '=Sheet1!$A$2:$A$7',
    values     => '=Sheet1!$B$2:$B$7',
);


$chart->set_y_axis( major_gridlines => { visible => 0 } );
$chart->set_legend( none => 1 );

# Temporary workaround for chart tick placement:
$chart->{_x_axis}->{_major_tick_mark} = 'in';
$chart->{_y_axis}->{_major_tick_mark} = 'cross';

$worksheet->insert_chart( 'D2', $chart, 25, 10 );

$workbook->close();

__END__

Output:

```
![image](https://cloud.githubusercontent.com/assets/94267/12292441/0b542e3c-b9e5-11e5-94de-e67e3b7e5514.png)

**Comment by wang-q** [comment]
Thanks for your response. It works.

**Comment by jmcnamara** [comment]
Added in version 0.87 on CPAN:

```perl

$chart->set_x_axis( major_tick_mark => 'none', minor_tick_mark => 'inside' );
$chart->set_y_axis( minor_tick_mark => 'cross' );

```

Thanks for the suggestion.
