### ISSUE TITLE
Feature request: provide a way to write booleans to cells

### ISSUE THREAD

**Issue by sblondeel** [jmcnamara/excel-writer-xlsx#156]
Booleans show up as "TRUE" or "FALSE" in Excel -- depending on the language, it is "VRAI" or "FAUX" in French for example -- but are stored as a 0/1 value in the <c> XML element in the worksheet.xml file.

If I believe the source code of the Python XLSX library and the observation of existing Excel files, this is accomplished with the t="b" XML attribute in the <c> XML element, like so:

    <c t="b">0</c> 
    <c t="b">1</c> 

I guess this could be added in the "Numerical formats" part of the documentation.

**Comment by jmcnamara** [comment]
Hi,

I've added this to the master branch. From the new docs:



> ####  `write_boolean( $row, $column, $value, $format )`

> Write an Excel boolean value to the cell specified by ``$row` and ``$column``:

>     $worksheet->write_boolean( 'A1', 1          );  # TRUE
    $worksheet->write_boolean( 'A2', 0          );  # FALSE
    $worksheet->write_boolean( 'A3', undef      );  # FALSE
    $worksheet->write_boolean( 'A3', 0, $format );  # FALSE, with format.

> A `$value` that is true or false using Perl's rules will be written as an Excel boolean `TRUE` or `FALSE` value.

Try it out and see if it meets requirements.

John.
--

**Comment by jmcnamara** [comment]
Uploaded to CPAN in as version 0.89.
