### ISSUE TITLE
How to convert the entire column in Excel to text format

### ISSUE THREAD

**Issue by Hari3288** [jmcnamara/excel-writer-xlsx#158]
Hi,

Could you please let me know how to convert the entire column in Excel file to text format. I am using the below code but it is formatting only that particular cell value. I want to format the entire column to text.

```perl
$worksheet->Keep_leading_zeros();
$my format1 = $workbook->add_format(num_format => '@');
$worksheet->write_string($ir,$ic,$value,$format1);

$ir - row index
$ic - column index
```

Thanks in advance.

**Comment by jmcnamara** [comment]
You can set the format for a column using [`set_column()`](http://search.cpan.org/~jmcnamara/Excel-Writer-XLSX/lib/Excel/Writer/XLSX.pm#set_column(_$first_col,_$last_col,_$width,_$format,_$hidden,_$level,_$collapsed_)).

Note that, as in Excel, a column format is overridden by a row format which is in turn overridden by a column format (this is explained in the above docs).
