### ISSUE TITLE
Feature request: Add Hyperlink to insert_image()

### ISSUE THREAD

**Issue by snethej** [jmcnamara/excel-writer-xlsx#161]
Being able to hyperlink an inserted image would be a nice feature to a cool library.

**Comment by jmcnamara** [comment]
I'll look into adding it.

**Comment by ArtemKuchin** [comment]
Need it too badly.
If added here i will migrate code from WriteExcel

**Comment by jmcnamara** [comment]
Initial suport for this feature has been added to master.

You can now do:

```perl
use Excel::Writer::XLSX;

my $workbook  = Excel::Writer::XLSX->new( 'text.xlsx' );
my $worksheet = $workbook->add_worksheet();

$worksheet->insert_image( 'E9', 'red.png',
                          {url => 'https://github.com/jmcnamara'} );

$workbook->close();

```

**Comment by jmcnamara** [comment]
This is now supported in Excel::Writer::XLSX version 1.02.
