### ISSUE TITLE
can somebody tell me how to do this(see the screenshot below)

### ISSUE THREAD

**Issue by haoziyeung** [jmcnamara/excel-writer-xlsx#164]
![image](https://cloud.githubusercontent.com/assets/16606564/15768409/14694468-2983-11e6-8648-1c6741cd9202.png)

**Comment by jmcnamara** [comment]
You can use the `text_wrap` format property to do that, see the docs:

http://search.cpan.org/dist/Excel-Writer-XLSX/lib/Excel/Writer/XLSX.pm#set_text_wrap%28%29

Also it is used in several places in the examples:

http://search.cpan.org/~jmcnamara/Excel-Writer-XLSX/lib/Excel/Writer/XLSX/Examples.pm
