### ISSUE TITLE
write_url Tool Tip

### ISSUE THREAD

**Issue by snethej** [jmcnamara/excel-writer-xlsx#165]
The documentation does not show the tool tip function parameter for write_url(), but it seems to be supported as $arg \[5\] (works in version 0.80, and still seems to be in the code in version 0.95).

Does the documentation need to be updated, or is this parameter going to be depricated?

**Comment by jmcnamara** [comment]
For now it is just an undocumented feature since, as far as I know, no-one ever asked for it. I just put it in for completeness at some stage.

If you are using it then I can add it to the documentation/

Anyway, feel free to use it, it won't be deprecated.

**Comment by snethej** [comment]
I'm using it, so I don't need it in the documentation at this point, and I won't worry about it going away. I just wanted to point it out in case you wanted it logged as a documentation issue you may to update someday.
Thx!

**Comment by jmcnamara** [comment]
Ok, thanks.
