### ISSUE TITLE
Feature request: Set the zipfile member timestamps to the workbook's timestamp

### ISSUE THREAD

**Issue by tsibley** [jmcnamara/excel-writer-xlsx#168]
There are two small sources of change between equivalent generations of the same XLSX document: the Excel workbook timestamps in `docProps/core.xml` and the zipfile member timestamps for each XML file.

Both timestamps default to "now".  The workbook timestamps are explicitly set to "now" in the Excel::Writer::XLSX code, and the zipfile member timestamps are drawn from the filesystem timestamps of the newly created temporarily files containing the XML documents.

This means that the final XLSX file generated doesn't remain byte-for-byte the same between two runs even though the contents are otherwise exactly the same.  In turn, the message digests (such as SHA-1) on the .xlsx files change too.  In my use case, I need the output file to be the same every time when given the same input.  The timestamps always being "now" prevent that.

The solution is two-part.

First, the workbook timestamp can already be manually set via `$workbook->set_properties( created => ... )`.  This eliminates the first problem by allowing the XML documents to be the same given the same input.

The second part of the solution is my request.  The zipfile member timestamps could be set to the workbook timestamp explicitly instead of implicitly drawing their timestamps from the temporary files.  When the workbook timestamp is allowed to default to "now", the zipfile member timestamps would be set to that same "now", and the behaviour is nearly equivalent to drawing the timestamps from the temporary files.  However, when the workbook timestamp is manually set, the final .xlsx file won't change between runs just because it was generated at a different time.

**Comment by tsibley** [comment]
The patch I previously wrote to do what I describe above is: https://github.com/jmcnamara/excel-writer-xlsx/pull/166/commits/ef2454f690ac65e88846375f103d75e58f1d5e88

**Comment by tsibley** [comment]
A workaround, without the patch above, looks like the following:

```
    $workbook->close
        or die "Error closing Excel file: $!";

    my $zip = Archive::Zip->new;
    $zip->read( "workbook.xlsx" ) == AZ_OK
        or die "Error reading zipfile: $!";

    $_->setLastModFileDateTimeFromUnix( 556387200 )
        for $zip->members;

    $zip->overwrite == AZ_OK
        or die "Error updating zipfile: $!";
```

I think it would be nicer to incorporate the patch into Excel::Writer::XLSX itself so that the question "How do I produce the same Excel file given the same input?" has the simple answer of "Set the `created` workbook property to a consistent value between runs".  I don't think it comes at much cost to Excel::Writer::XLSX itself.

**Comment by jmcnamara** [comment]
Hi Thomas,

> First, the workbook timestamp can already be manually set via $workbook->set_properties( created => ... ).

I am somewhat open to this part, although to date the only requests I've had to make this property public was to workaround a timezone bug that is now fixed. There was one other request from someone who was doing some sort of comparison testing on the xml files but the timestamp on the files wasn't an issue for them.

> I need the output file to be the same every time when given the same input. 
> ...
> The second part of the solution is my request. 

You don't say why, and you don't have to, but this request seems very user specific. 

If I add this feature in the Perl module I will probably have to add it in the Python/C/Lua versions as well and I'd like to see some additional user requests before I tackled that.

I'll leave the Feature Request open and if it gets enough +1s I'll add it in the future.

John

**Comment by tsibley** [comment]
The reason why is comparison testing, using message digests (such as SHA-1).  Excel is just one of several data formats in use, and unlike any other format I'm generating, the file changes every single time it's created regardless of if the contents have changed.

**Comment by jmcnamara** [comment]
Added in Excel::Writer::XLSX version 0.98. Thanks.
