### ISSUE TITLE
Bug: set bg_color to RGB code

### ISSUE THREAD

**Issue by konradbuessow** [jmcnamara/excel-writer-xlsx#169]
I have tried to set the background color of Excel cells with the Excel::Writer::XLSX module.
 
This works:
`my $format = $workbook->add_format();`
    `$format->set_bg_color('lime');`
    `$format->set_color('#7FFFD4');`
    `$format->set_color('white');`
This does not work (Background becomes white):
                `$format->set_bg_color('#7FFFD4');`
 
With `$format->set_bgcolor('#7FFFD4');` there is this error message:
 ```
Argument "#7FFFD4" isn't numeric in numeric ne (!=) at 
C:/Dwimperl/perl/site/lib/Excel/Writer/XLSX/Workbook.pm line 1149.
```

Here is some code that demonstrates the problem.

```perl
#!/usr/bin/perl -w

use strict;
use Excel::Writer::XLSX;

my $workbook  = Excel::Writer::XLSX->new("bgdemo.xlsx");
my $worksheet = $workbook->add_worksheet();
my $bgformat1 = $workbook->add_format(bg_color => 'silver', color => '#0000FF'); # #0000FF = blue
my $bgformat2 = $workbook->add_format(color => 'silver', bg_color => '#0000FF');

# Warning: Argument "#7FFFD4" isn't numeric in numeric ne (!=) 
# at C:/Dwimperl/perl/site/lib/Excel/Writer/XLSX/Workbook.pm line 1149.

$worksheet->write(0, 0, "Hi Excel!", $bgformat1);
$worksheet->write(1, 0, "Hi Excel!", $bgformat2);
__END__
```
Here is the resulting Excel file
[bgdemo.xlsx](https://github.com/jmcnamara/excel-writer-xlsx/files/329972/bgdemo.xlsx)

My automatically generated system details are as follows

```
Perl version   : 5.014002
OS name        : MSWin32
Module versions: (not all are required)
                 Excel::Writer::XLSX     	0.46
                 Spreadsheet::WriteExcel 	2.37
                 Archive::Zip            	1.30
                 XML::Writer             	0.615
                 IO::File                	1.15
                 File::Temp              	0.22
```

**Comment by jmcnamara** [comment]
Hi Konrad,

Thanks for the detailed report.

> My automatically generated system details are as follows
> ...
> Excel::Writer::XLSX 0.46

I would say that this is the source of the issue. The version of Excel::Writer::XLSX is almost 50 versions and 4 years behind the current release. :-)

When I run your example program with the latest version I get the following which looks like the output you expected:
![aa_image](https://cloud.githubusercontent.com/assets/94267/16304287/9e7a3bb6-394c-11e6-9a08-b6c838153780.png)

John

**Comment by konradbuessow** [comment]
Dear John,
Thanks a lot! I have installed the new version, that solved the problem.
Konrad


Date: Thu, 23 Jun 2016 06:13:33 -0700

**Comment by jmcnamara** [comment]
Hi Konrad, thanks for the update. Closing.
