### ISSUE TITLE
Protect Workbook

### ISSUE THREAD

**Issue by snethej** [jmcnamara/excel-writer-xlsx#170]
I know that $worksheet->protect() exists, but is there a method for protecting the workbook as well? I was not able to find one.

Thanks!

**Comment by jmcnamara** [comment]
Hi Snethej,

> is there a method for protecting the workbook as well?

Unfortunately not. From the [docs](http://search.cpan.org/dist/Excel-Writer-XLSX/lib/Excel/Writer/XLSX.pm#protect(_$password,_\%options_)):

> Note, the worksheet level password in Excel provides very weak protection. It does not encrypt your data and is very easy to deactivate. Full workbook encryption is not supported by Excel::Writer::XLSX since it requires a completely different file format and would take several man months to implement.

And at this stage you could replace man months with man years.

John
