### ISSUE TITLE
Conditional Formatting Stop if True

### ISSUE THREAD

**Issue by snethej** [jmcnamara/excel-writer-xlsx#172]
The following code snippets:

$worksheet->conditional_formatting( 'T2:W2',
    {
        type     => 'cell',
        criteria => 'between',
        minimum  => '$AM$2',
        maximum  => 100,
        format   => $greenNum,
        stop_if_true => 0
    }
);
$worksheet->conditional_formatting( 'T2:W2',
    {
        type     => 'cell',
        criteria => 'between',
        minimum  => '=(1.1*$AM$2-10)',
        maximum  => '$AM$2',
        format   => $yellowNum,
        stop_if_true => 0
    }
);
$worksheet->conditional_formatting( 'T2:W2',
    {
        type     => 'cell',
        criteria => 'between',
        minimum  => 0,
        maximum  => '$AM$2',
        format   => $redNum,
        stop_if_true => 1
    }
);

results in that all three rules have the “Stop If True” checked in the resulting Excel file instead of just the last one.

The server currently is running v0.88, but I could not find any changes since then related to it (so I may have missed it). I am trying to get the provider to upgrade to the latest to see if that helps.

**Comment by jmcnamara** [comment]
Hi,

Can you post a small working example that demonstrates the issue. 

John

**Comment by snethej** [comment]
`use strict;         # Always a good idea.
use warnings;

use Excel::Writer::XLSX;    # Current system version: 0.88

my %stdFnt      = ( font  => 'Arial', size  => 10);
my %stdFnt_left = ( %stdFnt, align => 'left');

my $wrkBk = Excel::Writer::XLSX->new( 'writer.xlsx' );

my $format = $wrkBk->add_format( %stdFnt_left,   num_format => '@', text_wrap => '1' );
my $lnkFmt = $wrkBk->add_format( %stdFnt_left, color => 'blue', underline => 1 );
my $numFmt = $wrkBk->add_format( %stdFnt,  num_format => '##0.0' );

my $wrkSht = $wrkBk->add_worksheet( 'Data' );

my $url   = 'http://search.cpan.org/~jmcnamara/Excel-Writer-XLSX-0.80/lib/Excel/Writer/XLSX.pm';
my $label = 'Excel Writer on CPAN';
my $tip   = 'Is this a Tip?';

$wrkSht->write_url('A1', $url, $lnkFmt, $label, $tip); 

my $yellowNum = $wrkBk->add_format();
$yellowNum->copy( $numFmt );
$yellowNum->set_bg_color( '#FFFF99' );

my $greenNum = $wrkBk->add_format();
$greenNum->copy($yellowNum);
$greenNum->set_bg_color( '#CCFFCC' );

my $redNum = $wrkBk->add_format();
$redNum->copy($yellowNum);
$redNum->set_bg_color( '#FF99CC' );

$wrkSht->conditional_formatting( 'A2:D2',
    {
        type     => 'cell',
        criteria => 'between',
        minimum  => '$E$2',
        maximum  => 100,
        format   => $greenNum,
        stop_if_true => 0
    }
);
$wrkSht->conditional_formatting( 'A2:D2',
    {
        type     => 'cell',
        criteria => 'between',
        minimum  => '=(1.1*$E$2-10)',
        maximum  => '$E$2',
        format   => $yellowNum,
        stop_if_true => 0
    }
);
$wrkSht->conditional_formatting( 'A2:D2',
    {
        type     => 'cell',
        criteria => 'between',
        minimum  => 0,
        maximum  => '$E$2',
        format   => $redNum,
        stop_if_true => 1
    }
);

my @data = (91.6, 90.2, 90.7, 86.6, 91.0);

$wrkSht->write('A2', \@data, $numFmt );
`

**Comment by jmcnamara** [comment]
Hi,

That is a bug. I'll fix it soon. In the meantime don't define `stop_if_true` if you don't need it.

John

**Comment by f20** [comment]
Seeing it's my bug I have provided a possible fix as a pull request.  Sorry about that.
