### ISSUE TITLE
Problem using contact group  address that start with # as a email link

### ISSUE THREAD

**Issue by jhuijsing** [jmcnamara/excel-writer-xlsx#173]
I have problem in our organization we use the # to indicate a mailing group/contact list

The following code was removing the pound/hash symbol
     2769         # Split url into the link and optional anchor/location.
     2770           ( $url, $url_str ) = split /#/, $url;

I modified it to this
     2769         # Split url into the link and optional anchor/location.
     2770         if ( $url !~ /:#/ ) {
     2771           ( $url, $url_str ) = split /#/, $url;
     2772         }

**Comment by jmcnamara** [comment]
What is an example address? Something like this?:

     #foo@bar.com

**Comment by jhuijsing** [comment]
yes like that.
