### ISSUE TITLE
File::Temp->newdir( DIR => $self->{_tempdir} )

### ISSUE THREAD

**Issue by daominh6879** [jmcnamara/excel-writer-xlsx#176]
Sorry for bordering you again!
When I try to use this script, I encounter with a problem
(in cleanup) Can't locate object method "newdir"
Can you help me with this problem?
Thank you very much!

**Comment by jmcnamara** [comment]
That is probably because your version of `File::Temp` is too old. You need `File::Temp` >= 0.19.

**Comment by daominh6879** [comment]
Hi,

Thanks a lot. I can do it now.

BRs,
Hung
