### ISSUE TITLE
Out of Memory Exception in perl script.

### ISSUE THREAD

**Issue by Hari3288** [jmcnamara/excel-writer-xlsx#178]
Hi John,

Can you please help to resolve the below issue and let me know if you need any further info.

We have process in our application where perl script will convert the excel file tab's to text file, Since the
 file been is having around 181352 records, when it tries to convert the Excel file to text, "Out of Memory" exception is fired.

Note: We have same perl script in another unix server and it is working fine without any issue also we compared both the perl scripts and both are equal.

Error occurred in LOG file:

+ xls=IRP-EXPORT-VVT-Tables Team-2016-11-05_06_112016-11-08 08:16:44.969.xlsx
+ bid=2606
+ perl ./cnv_xls_txt.pl 'IRP-EXPORT-VVT-Tables Team-2016-11-05_06_112016-11-08 08:16:44.969.xlsx' 2606
"my" variable $mo masks earlier declaration in same scope at ./cnv_xls_txt.pl line 59.
Ambiguous use of ${if} resolved to $if at ./cnv_xls_txt.pl line 141.
Out of memory!

[xls_to_txt.txt](https://github.com/jmcnamara/excel-writer-xlsx/files/577827/xls_to_txt.txt)

**Comment by jmcnamara** [comment]
Hi @Hari3288,

You can turn on optimimation mode to reduce the memory used by Excel::Writer::XLSX down to a small constant level. Note, if this mode you will have to write all data in row x column order. From the [docs](http://search.cpan.org/dist/Excel-Writer-XLSX/lib/Excel/Writer/XLSX.pm#set_optimization()):



>**set_optimization()**

>The `set_optimization()` method is used to turn on optimizations in the Excel::Writer::XLSX module. Currently there is only one optimization available and that is to reduce memory usage.

>```perl
    $workbook->set_optimization();
```

>See "SPEED AND MEMORY USAGE" for more background information.

>**Note**, that with this optimization turned on a row of data is written and then discarded when a cell in a new row is added via one of the Worksheet write_*() methods. As such data should be written in sequential row order once the optimization is turned on.

>This method must be called before any calls to add_worksheet().

John

**Comment by Hari3288** [comment]
Hi John,

If i understand correctly while creating the Excel itself set the optimization function, So that memory it will create any issue while creating the text file from Excel. Am i right?

**Comment by jmcnamara** [comment]
Yes.

**Comment by Hari3288** [comment]
Hi John,

Thanks a lot for your response, Let me check on that and let you know for any queries.

**Comment by Hari3288** [comment]
Hi John,

Could you please let me know why this issue is not happening in other unix server as we have same set of code. is there is any configuration needs to be changed in the server where we are facing issue?

**Comment by jmcnamara** [comment]
> Could you please let me know why this issue is not happening in other unix server as we have same set of code

Perhaps the other server has more memory.

**Comment by Hari3288** [comment]
Hi John,

I too though the same and requested the unix admin to check the memory space for the corresponding user id(User id where it triggers the perl) but they replied that the memory is unlimited for that user also the corresponding server has 262G of space out of 20% are used so far.

Could you please let me know if i need to check in other perspective to increase the memory?

**Comment by jmcnamara** [comment]
Hi @Hari3288,

I'm afraid this isn't something that I can help you with.

John
