### ISSUE TITLE
Issue when running excel::writer::xlsx based code after packing it with pp

### ISSUE THREAD

**Issue by wolh** [jmcnamara/excel-writer-xlsx#180]
I'm running into issues with excel::writer.xlsx (rel. 0.95) based code when packing it with PAR::packager (rel. 1.036) and running the executable for the specifc case of embedded scatter-type charts. The executable crashes issueing the message: Chart type 'Scatter' not supported in add_chart().
This also happens when packing the distribution example chart_scatter.pl and subsequently running the executable.
All code runs perfectly when directly run as a Perl script.
I'm not sure whether this is a excel::writer::xlsx issue or or something associated with pp.
Other chart types seem to work fine, although I have not thoroughly tested all of them.
I'm not attaching any code since chart_scatter.pl and pp are coming directly with the distribution kit.

**Comment by ale275** [comment]
Hi @wolh 
as found somewhere here you have to explicitly add the chart in your code using

use Excel::Writer::XLSX::Chart::Scatter;

this way your packed app will work fine
Ale

**Comment by jmcnamara** [comment]
Hi,

You probably just need to include `use Excel::Writer::XLSX::Chart::Scatter` in your program so that Par finds it. From the [docs](http://search.cpan.org/dist/Excel-Writer-XLSX/lib/Excel/Writer/XLSX.pm#BUGS):

> **Perl packaging programs can't find chart modules.**
>
>When using Excel::Writer::XLSX charts with Perl packagers such as PAR or Cava you should explicitly include the chart that you are trying to create in your use statements. This isn't a bug as such but it might help someone from banging their head off a wall:
>
>```perl
    ...
    use Excel::Writer::XLSX;
    use Excel::Writer::XLSX::Chart::Column;
    ...
```

John

**Comment by jmcnamara** [comment]
Thanks @ale275
