### ISSUE TITLE
How to set Date format in Excel using perl script?

### ISSUE THREAD

**Issue by Hari3288** [jmcnamara/excel-writer-xlsx#185]
Hi John,
![cell format](https://cloud.githubusercontent.com/assets/11457753/24357180/77ddfed6-131a-11e7-8a08-7cfad97fb469.jpg)

We have requirement to set the cell format as date in excel, So can someone please help to achieve this through perl.

Please refer the attachment that show how the cell format should be.

**Comment by jmcnamara** [comment]
You can do this by using the same format used by Excel. You can see this by changing to the "Custom" part of the dialog above. It is generally `'dd/mm/yyyy'`. Alternatively you can use one of the built in formats that E::W::X represents with and integer. See the two alternatives in the example below:

```perl
#!/usr/bin/perl

use strict;
use warnings;
use Excel::Writer::XLSX;

my $workbook   = Excel::Writer::XLSX->new( 'test.xlsx' );
my $worksheet  = $workbook->add_worksheet();

$worksheet->set_column( 'A:A', 20 );

my $date_format1 = $workbook->add_format( num_format => 14 );
my $date_format2 = $workbook->add_format( num_format => 'dd/mm/yyyy' );

$worksheet->write( 'A1', 43113, $date_format1 );
$worksheet->write( 'A2', 43113, $date_format2 );

$workbook->close();

__END__

```
Output:

![aa_image](https://user-images.githubusercontent.com/94267/45614700-41e6b480-ba62-11e8-946f-39550fa0781d.png)

See the [num_format](https://metacpan.org/pod/distribution/Excel-Writer-XLSX/lib/Excel/Writer/XLSX.pm#set_num_format()) section of the docs.
