### ISSUE TITLE
Character Encoding

### ISSUE THREAD

**Issue by snethej** [jmcnamara/excel-writer-xlsx#187]
I looked through the issues and did not see related issues, except maybe #129 and #159, but they didn't seem to apply.

My current version is lagging, but I have to have justification for our admins to upgrade.  If this is fixed in later versions, I may be able to push an upgrade to the current version.

Using the following test file:

```perl
use Excel::Writer::XLSX;    # Current version: 0.88
#use utf8;
 
my $wrkBk = Excel::Writer::XLSX->new( 'encodeTst.xlsx' );
my $wrkSht  = $wrkBk->add_worksheet();
my $string = q|We’re in a re-plan cycle now.|; # apostrophe is \x92
$wrkSht->write_string(2,2, $string );
```
I get a value that cannot be displayed in Excel 2013.  If I put the above string into the next row of the spreadsheet and save it, I can see the apostrophe in the cell.  In the resulting file, sharedStrings.xml, the values are shown like:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="2" uniqueCount="2"><si><t>WeÂ’re in a re-plan cycle now.</t></si><si><t>Weâ€™re in a re-plan cycle now.</t></si></sst>
```
The characters in the string written by Excel::Writer::XLSX are \xC2 \x92, whereas the characters written directly into Excel turn out to be \xE2 \x80 \x99.

Once place that seems to agree with the values as typed into Excel is [http://www.i18nqa.com/debug/utf8-debug.html](http://www.i18nqa.com/debug/utf8-debug.html), although I'm not very experienced in decoding UTF-8.

If I uncomment `use utf8;` in the code, I get the following error:

```
perl -w encodeTst.pl
        (in cleanup) Malformed UTF-8 character (fatal) at /usr/share/perl5/Excel/Writer/XLSX/Package/SharedStrings.pm line 199.

```
[encodeTst.xlsx](https://github.com/jmcnamara/excel-writer-xlsx/files/1119812/encodeTst.xlsx)

**Comment by snethej** [comment]
I may have found a solution to my issue, using the following script:

```
use Excel::Writer::XLSX;    # Current version: 0.88
use Encode;

my $wrkBk = Excel::Writer::XLSX->new( 'encodeTst.xlsx' );
my $wrkSht  = $wrkBk->add_worksheet();
 
my $string = q|We’re in a re-plan cycle now.|; # apostrophe is \x92
 
$string = Encode::decode(cp1252 => $string);
$wrkSht->write_string(2,  2, $string );
```
The character appears to have been created from Windows encoding, so decoding it before the `write_string` seems to have solved my issue.

Thanks for listening!  :)

**Comment by jmcnamara** [comment]
The code should work. You just need to encode the file as UTF-8 using whatever editor you usually use and include the `use utf-8;` that you have currently commented out.

I encode and ran the following:

```perl
use Excel::Writer::XLSX;    # Current version: 0.88
#use utf8;
 
my $wrkBk = Excel::Writer::XLSX->new( 'encodeTst.xlsx' );
my $wrkSht  = $wrkBk->add_worksheet();
my $string = q|We’re in a re-plan cycle now.|; # apostrophe is \x92
$wrkSht->write_string(2,2, $string );
```
And got this output:

![aa_image](https://user-images.githubusercontent.com/94267/27801527-670ea792-6016-11e7-8d26-ee1507b8a549.png)

If you are reading data from an external file with a non-ASCII encoding and translating it to Excel then see the [various unicode_*.pl](http://search.cpan.org/~jmcnamara/Excel-Writer-XLSX/lib/Excel/Writer/XLSX/Examples.pm#Example:_unicode_2022_jp.pl) examples in the distro.

P.S., the Excel::Writer::XLSX version doesn't matter for this.

**Comment by jmcnamara** [comment]
> I may have found a solution to my issue, using the following script:

Ok. Our posts overlapped. :-)

Closing.
