### ISSUE TITLE
Question: support sort with autofilter?

### ISSUE THREAD

**Issue by joez** [jmcnamara/excel-writer-xlsx#190]
Can I enable the "sort by" with autofilter enabled on a column?
just like http://openpyxl.readthedocs.io/en/default/filters.html?highlight=filter

**Comment by jmcnamara** [comment]
Technically it would be possible to add similar functionality.

However, the linked feature doesn't actually sort the data, it just turns on the filter symbol to indicate that the data is sorted. Is that what you require?

From the linked docs:

>Filters and sorts can only be configured by openpyxl but will need to be applied in applications like Excel. This is because they actually rearranges or format cells or rows in the range.

and

> This will add the relevant instructions to the file but will neither actually filter nor sort.

So the actual return on investment on this is low, which is why I haven't implemented it in the past. Also, it would mislead users into thinking that it will sort the data for them, which it doesn't.

**Comment by joez** [comment]
Actually, I am asking whether it is possible to filter a column with sort condition, the data should be sorted accordingly

From the OpenPyXL's docs:
> Filters and sorts can only be configured by openpyxl but will need to be applied in applications like Excel. This is because they actually rearranges or format cells or rows in the range.

I don't quite understand what it really means, I suppose once the relevant instructions are set, the cells will be arranged by the Excel application the file is opened. If that is not the case, then as you said, it will mislead users and this is not what I want.

**Comment by jmcnamara** [comment]
> Actually, I am asking whether it is possible to filter a column with sort condition, the data should be sorted accordingly

That isn't possible via the file format. Excel sorts data at runtime via the interface but you can't trigger that from the xlsx file.

The best thing to do is sort your data in Perl before writing it.

> I don't quite understand what it really means,

What it means is that sorting can only be done in Excel. OpenPyXL sets a flag to indicate the data is sorted but it is up to the user to actually sort the data.

**Comment by joez** [comment]
Got it, thanks

I can't sort the data in Perl because the data is calculated by a Excel formula at runtime

Is it possible to create a Excel workbook as a template manually, and then insert it (regard itself as read-only) into the target workbook generated in Perl?

**Comment by jmcnamara** [comment]
> Is it possible to create a Excel workbook as a template manually, and then insert it

Unfortunately not.

You may be able to do what you want by adding a Macro: http://search.cpan.org/dist/Excel-Writer-XLSX/lib/Excel/Writer/XLSX.pm#WORKING_WITH_VBA_MACROS
