### ISSUE TITLE
Feature Request: Format legend area

### ISSUE THREAD

**Issue by ekantons** [jmcnamara/excel-writer-xlsx#191]
Please add the capability to format the legend area, in the same way that the chart area and plot area can be formatted (border, fill, gradient, etc.).
The attached diff file shows the small number of changes needed to Chart.pm for this additional feature.
The changes shown in the diff file have been tested successfully.

[diff_v0.95a.txt](https://github.com/jmcnamara/excel-writer-xlsx/files/1249478/diff_v0.95a.txt)

**Comment by jmcnamara** [comment]
Thanks for the patch. I'll look into it.

John

**Comment by jmcnamara** [comment]
This feature is now available upstream in master. It will be rolled into the next release.

**Comment by jmcnamara** [comment]
Feature request added to Excel::Writer::XLSX CPAN release 0.99.
