### ISSUE TITLE
Feature Request: add_series return value

### ISSUE THREAD

**Issue by ekantons** [jmcnamara/excel-writer-xlsx#192]
I suggest that add_series should return the index number of the series, suitable to be used to delete the series from the legend (delete_series array argument to set_legend).  In version 0.95, add_series returns (not purposefully and undocumented) the total number of series in the chart, but this is a 1-based count, and deleting the series from the legend is a zero-based index.  So, I suggest that the return value of add_series be made overt, and decremented by 1.

```perl
    my $_series_index = push @{ $self->{_series} }, \%arg; # v0.95b
    return $_series_index - 1; # v0.95b
```

[diff_v0.95b.txt](https://github.com/jmcnamara/excel-writer-xlsx/files/1249497/diff_v0.95b.txt)

**Comment by jmcnamara** [comment]
Good suggestion.

**Comment by jmcnamara** [comment]
I'm cleaning up feature requests that I'm probably not going to get around to and/or didn't generate enough interest. Unfortunately this is one of them. Closing as Won't Fix.
