### ISSUE TITLE
there is no documentation for date specifiers

### ISSUE THREAD

**Issue by aliber4079** [jmcnamara/excel-writer-xlsx#194]
hi, is there a way to specify 24-hour time format

**Comment by jmcnamara** [comment]
It should be the same format as in Excel. What format do you use in Excel?

**Comment by aliber4079** [comment]
'dd/mm/yy hh:mm:ss.000', only shows am and pm

**Comment by jmcnamara** [comment]
And what does it show in Excel?

**Comment by aliber4079** [comment]
I get it now, the format comes from Excel, I was looking for something like the man page of strftime

sorry about that!

**Comment by jmcnamara** [comment]
Good stuff.
