### ISSUE TITLE
Issue: Can't locate object methode "set_chararea"

### ISSUE THREAD

**Issue by gcouture44** [jmcnamara/excel-writer-xlsx#195]
Can't locate object method
"set_chararea" via package "Excel::Writer::XLSX::Chart::Pie" at tmp_excelT572.pl
line 31.

We have 4 production server and for some reason, the same script give this error on 1 of them.  We cant figure out why... 

We currently using the lasted version.

Thank you for the help

**Comment by jmcnamara** [comment]
Hi,

That looks like a typo in your code. The method name should be `set_chartarea()`.

John

**Comment by gcouture44** [comment]
you were right.... thank you.  so simple sometime,  we were blind :-)

**Comment by jmcnamara** [comment]
No problem. Closing.
