### ISSUE TITLE
how to export charts?

### ISSUE THREAD

**Issue by haoziyeung** [jmcnamara/excel-writer-xlsx#196]
hello all:
    i'm using Excel::Writer::XLSX::Chart to create excel charts,but i want to export this charts to png or some else format,and i don't want to use macros,anyone know how to do this?

**Comment by haoziyeung** [comment]
![qq 20171023163932](https://user-images.githubusercontent.com/16606564/31879702-c65bebc2-b810-11e7-8724-a4252c44afeb.png)

**Comment by jmcnamara** [comment]
Unfortunately that isn't possible with Excel::Writer::XLSX.

Charts are stored in an xlsx file in XML format. Only Excel, or a similar application, can convert them to an image.

I know that you say that you don't want to use macros but I doubt that there is any other way to do it and get an image that is like what Excel would export.

**Comment by haoziyeung** [comment]
thanks
