### ISSUE TITLE
Feature Request : add sort function to autofilter table column

### ISSUE THREAD

**Issue by ailangous** [jmcnamara/excel-writer-xlsx#197]
There is no way to sort ascending or descending on a autofilter table column

**Comment by jmcnamara** [comment]
Unfortunately sort isn't a property of the file format and so cannot be implemented by Excel::Writer::XLSX. So this is a `won't fix`.

In Excel sorting is computed at runtime. You may be able to emulate this in Perl by sorting your data before writing it to the autofilter region.
