### ISSUE TITLE
Feature request:   read(), read_row(), read_col() as inverse functions to write, write_row, write_col.

### ISSUE THREAD

**Issue by dwright** [jmcnamara/excel-writer-xlsx#200]
It would be nice if there was a way that I could get values back that I've already stored with a previous call to `write()`. 

This would be super-helpful to me when making calls to `write_formula()` when I need to provide the formula value as the 5th argument.

**Comment by jmcnamara** [comment]
Hi Dan,

Thanks for the suggestion.

> It would be nice if there was a way that I could get values back that I've already stored with a previous call to write().

That isn't possible by design. It is best to treat Excel::XLSX::Writer as a black box and rely on Perl data structures to store any data that you might want to reuse later.

Sorry about that.

John
