### ISSUE TITLE
Use of uninitialized value $_[0] in pattern match (m//)

### ISSUE THREAD

**Issue by labster** [jmcnamara/excel-writer-xlsx#206]
I got a
`Use of uninitialized value $_[0] in pattern match (m//) at /usr/local/lib/perl5/site_perl/Excel/Writer/XLSX/Format.pm line 465.`

```perl
my $bgcolor = undef;
$wb->add_format(
      align        => "left",
      border       => 1,
      border_color => "black",
      fg_color     => $bgcolor,
    );
```

It's pretty obvious what to do here -- move the defined check at line 470 up before the regex in 465.  Unless you want to warn here, in which case you should be more explicit to the user.  But there's no warning on any other invalid input, so `undef` seems like the least of your worries here.

Mainly my use case was trying to take the default color if a condition was false -- using undef seemed like the clearest approach.  Clearer than `($bgcolor ? (fg_color => $bg_color) :() ),` anyway.

**Comment by jmcnamara** [comment]
Fixed in version 0.98. Thanks.
