### ISSUE TITLE
automatically resize column width?

### ISSUE THREAD

**Issue by hhg7** [jmcnamara/excel-writer-xlsx#210]
Hello,

is there a way to get the columns automatically resized, which is normally achieved by double clicking on the line between columns?

thanks,
-Dave

**Comment by jmcnamara** [comment]
Unfortunately, there is no way to specify "AutoFit" for a column in the Excel file format. 

This feature is only available at runtime from within Excel. It is possible to simulate "AutoFit2 in your application by tracking the maximum width of the data in the column as your write it and then adjusting the column width at the end.
