### ISSUE TITLE
Does not crash when receiving uninitialized values

### ISSUE THREAD

**Issue by hhg7** [jmcnamara/excel-writer-xlsx#212]
The program does not crash or even give a warning when I give it (not intentionally) something like this:

`$worksheet -> write(0,0, $uninitialized{$hash}{$value});`

I think it would be great if Excel::Writer::XLSX could be modified to print warnings about uninitialized values in these situations.  Excel::Writer::XLSX somehow bypasses Perl's own mechanism about uninitialized values.

**Comment by jmcnamara** [comment]
> The program does not crash or even give a warning when I give it (not intentionally) something like this

Correct. It is the intentional and documented behaviour that undef values are handled by `write()`. See: https://metacpan.org/pod/distribution/Excel-Writer-XLSX/lib/Excel/Writer/XLSX.pm#write(-$row,-$column,-$token,-$format-)

In particular:

> The `write()` method will ignore empty strings or undef tokens unless a format is also supplied. As such you needn't worry about special handling for empty or undef values in your data. See also the `write_blank()` method.
