### ISSUE TITLE
Hyperlink to different worksheets?

### ISSUE THREAD

**Issue by hhg7** [jmcnamara/excel-writer-xlsx#215]
Is it possible to write a hyperlink to a different worksheet, and if so, could you show an example? The hyperlinks in the manual page look more for email and URL.  This may be a feature request.

**Comment by jmcnamara** [comment]
> Is it possible to write a hyperlink to a different worksheet, and if so, could you show an example?

Yes. 

See the `internal:` links in the `write_url()`docs: https://metacpan.org/pod/distribution/Excel-Writer-XLSX/lib/Excel/Writer/XLSX.pm#write_url(-$row,-$col,-$url,-$format,-$label-)

Also, see this example in the distro: https://metacpan.org/source/JMCNAMARA/Excel-Writer-XLSX-0.98/examples/hyperlink2.pl
