### ISSUE TITLE
Unreadable Content Error in Excel

### ISSUE THREAD

**Issue by Chitranshagarwal2000** [jmcnamara/excel-writer-xlsx#216]
I am new to perl, so sorry if i make a mistake in coding and have to bother you.
I reached out to many experts but none were able to solve the problem.

I am trying to query a database (DB2) and store the output in Excel. The data is about 250k rows, if the data is less than there is no error but with this volume of data, it throws out an error (pasted below) and if i click on repair, some data is replaced with "inf"

![image](https://user-images.githubusercontent.com/42971454/45067862-8f6a3580-b0e2-11e8-8d3e-97645d44da15.png)

Below is the script snippet

````perl
while (my $sqlStatement = <SQL>) {
 $mSQL = $dbh->prepare($sqlStatement)
  or die "Can't prepare $sqlStatement";
 $mSQL->execute()
  or die "Can't execute $sqlStatement";
}

my $workbook = Excel::Writer::XLSX->new($ARGV[2]);
$workbook->set_tempdir( '/tempDir/' );
$workbook->set_optimization();
my $worksheet = $workbook->add_worksheet();
$worksheet->keep_leading_zeros();

my $row = 0;
my $column = 0;

my @emptyRow=();

$worksheet->write_row($row++,$column, [@{$mSQL->{NAME_uc}}]);
$worksheet->write_row($row++,$column,[@emptyRow]);

while (my @row = $mSQL->fetchrow_array) {
	$worksheet->write_row($row++,$column, [@row]);#, $cellFormat);
	$count++;
}
$workbook->close();
```

Please let me know if any further information is required.
Thanks for your time

Regards

**Comment by jmcnamara** [comment]
There isn't anything in the code that you supplied that should cause that issue. In general the only time errors like that occur is if there are overlapping merged ranges or tables.

For simpler data writing, like in your example, you shouldn't encounter an issue like this.

**Comment by Chitranshagarwal2000** [comment]
Thanks for your reply John,
Sorry to be a pain but i really didn't understand that. I am actually querying a complex view for the data and the SQL is quite large.
Can this be the reason for this?

Thank you for your time

**Comment by jmcnamara** [comment]
> some data is replaced with "inf"

I missed the part about "inf" in your question. That is probably what is causing the issue. 

Excel doesn't have a way of writing "inf" as a number so you will have to filter them out of your data or replace them with strings. 

Or possibly some data that looks like a number, such as `1E310`, is being interpreted by write() as a number, which in turn get converted to infinity. See also #72 and #73 for some background.

**Comment by Chitranshagarwal2000** [comment]
Thanks for the response, this indeed is the case as the values which are getting converted to "inf" contain alphanumeric characters, and as per the threads you mentioned one of the possible solution is to modify or recreate the module file and use write_string subroutine instead of write, but thats not possible for me as all the modules are stored in a secure location and i can't edit them.

Is there a way to use write_string method to write the rows.

Regards

**Comment by jmcnamara** [comment]
> Is there a way to use write_string method to write the rows.

The easiest way is to unroll `write_roll()` into a simple for loop and write each of the column elements with the correct type. I.e, `write_number()` for numbers and `write_string()` for strings, etc.

If you want to change the behaviour of `write()`, and thus `write_row()` you could add a ["write handler"](https://metacpan.org/pod/Excel::Writer::XLSX#add_write_handler(-$re,-$code_ref-)) to your program. For example:

```perl
#!/usr/bin/perl

use strict;
use warnings;
use Excel::Writer::XLSX;


my $workbook  = Excel::Writer::XLSX->new( 'write_handler5.xlsx' );
my $worksheet = $workbook->add_worksheet();


# Add a handler to match any numbers in order to check for and handle
# infinity.
$worksheet->add_write_handler( qr[\d], \&write_with_infinity );


# The following function is used by write() to pre-process any the data when a
# match is found. If it finds something that looks like a number but evaluates
# to infinity it write it as a string.
sub write_with_infinity {

    my $worksheet = shift;
    my @args      = @_;
    my $token     = $args[2];

    # Check if token looks like a number, in the same way as write().
    if ( $token =~ /^([+-]?)(?=[0-9]|\.[0-9])[0-9]*(\.[0-9]*)?([Ee]([+-]?[0-9]+))?$/ ) {

	# Check for infinity.
	$token = $token + 0;

	if ($token =~ /Inf/) {

	    # Write the value as a string instead of a number.
	    return $worksheet->write_string( @args );
	}
    }

    # Reject the match and return control to write()
    return undef;
}

$worksheet->set_column('A:A', 35);

# Write some numbers until we reach infinity.
$worksheet->write( 'A1',  '2E3'    );
$worksheet->write( 'A2',  '2E30'   );
$worksheet->write( 'A3',  '2E300'  );
$worksheet->write( 'A4',  '2E3000' );
$worksheet->write( 'A5', '-2E3'    );
$worksheet->write( 'A6', '-2E30'   );
$worksheet->write( 'A7', '-2E300'  );
$worksheet->write( 'A8', '-2E3000' );


$workbook->close();

__END__

```
**Output**. Notice the string to the left and the numbers to the right:


![aa_image](https://user-images.githubusercontent.com/94267/45960234-ad58f500-c013-11e8-9ebd-6a303276612d.png)

However, in your case I would think that the first, simpler, approach would be better.
