### ISSUE TITLE
How to write an empty number?

### ISSUE THREAD

**Issue by kevinpacheco** [jmcnamara/excel-writer-xlsx#221]
Is there way to write an empty number to a cell? I'm aware of "write_blank", but it poses a couple of issues:
* I'm writing an application that builds a Perl script and executes it. Having to test if the number is empty and use "write_blank" instead of "write_number" adds more IF/THEN overhead. It would save some headaches if something like `$worksheet->write_number(0,0,,$format);` could work for this purpose
* "write_blank" doesn't format the cell as specified
```
use Excel::Writer::XLSX;
$workbook = Excel::Writer::XLSX->new('test.xlsx');
$worksheet = $workbook->add_worksheet();
$fmt_dec2 = $workbook->add_format(num_format => '0.00');
$worksheet->write_number(0,0,,$fmt_dec2);
#$worksheet->write_number(1,0,'',$fmt_dec2);
$worksheet->write_number(2,0,\0,$fmt_dec2);
$worksheet->write_blank(3,0,'',$fmt_dec2);
$worksheet->write_number(4,0,1.234,$fmt_dec2);
$workbook->close();
```
(I had to comment out line 6 because — unsurprisingly — it throws an error: Argument "" isn't numeric in addition (+) at /usr/local/share/perl/5.22.1/Excel/Writer/XLSX/Worksheet.pm line 2193.)

Here's what I get in the resulting sheet:
* In cell A1, 52627008, formatted as general
* In cell A2, nothing, formatted as general
* In cell A3, 38798440, formatted correctly as a number with 2 decimal places (appears as 38798440.00)
* In cell A4, nothing, formatted as general
* In cell A5, 1.234, formatted correctly as a number with 2 decimal places (appears as 1.23)

In Excel it's possible to format a cell (as, say, a number with 2 decimal places) without entering a value. I can't seem to be able to do that with Excel::Writer::XLSX.

**Comment by jmcnamara** [comment]
>  I'm writing an application that builds a Perl script and executes it. Having to test if the number is empty and use "write_blank" instead of "write_number" adds more IF/THEN overhead. It would save some headaches if something like `$worksheet->write_number(0,0,,$format);` could work for this purpose

This is basically what the `write()` function does. See the [docs](https://metacpan.org/pod/distribution/Excel-Writer-XLSX/lib/Excel/Writer/XLSX.pm#write(-$row,-$column,-$token,-$format-)).

John
