### ISSUE TITLE
Why is there no 'RemoveWorksheet'?  Can it be added?

### ISSUE THREAD

**Issue by DavidAyliffe** [jmcnamara/excel-writer-xlsx#222]
I need to remove a worksheet.

This method is essential in any XLSX writer module.

Can it please be added.

Thanks

**Comment by jmcnamara** [comment]
> Can it please be added.

No. Excel::Writer::XLSX doesn't allow you to modify an existing workbook.

**Comment by DavidAyliffe** [comment]
thanks Mr. McNamara for the quick reply.

is there a fundamental reason why it can't be added?

**Comment by DavidAyliffe** [comment]
Right, this is going to sound a little retarded.

I create many worksheets.  But one in particular is noteworthy. It may be the case that due to various permutations, nothing ever gets written to this sheet.  Hence I want to delete it.

I know, the best thing would be to not create it in the first place but sometimes it's not that simple.

A 'remove' method would be a great addition to an excellent module too.  I'm sure many others would appreciate it.

**Comment by jmcnamara** [comment]
> It may be the case that due to various permutations, nothing ever gets written to this sheet. Hence I want to delete it.

Ok, got it.

Unfortunately that feature won't be added since it could potentially break some features that rely on the worksheet index. There aren't any currently but there may be in the future.

So unfortunately you will need to handle it from your application.
