### ISSUE TITLE
write_formula without value defaults to zero rather than calculated formula

### ISSUE THREAD

**Issue by soldemuth** [jmcnamara/excel-writer-xlsx#225]
Hi John, 

When calling `write_formula` without a value, as suggested in the documentation, upon opening the resulting XLSX document (I tested Excel 365 and LibreOffice) the calculated cell defaults to zero.

To force spreadsheet applications to calculate the formula value on document open, you might want to either not write forumla `<v>` nodes at all or include empty `<v></v>` nodes. Either worked for Excel 365 and LibreOffice.

I suggested a quick fix, where an empty `<v>` node is still written, here: #224 

Please let me know if you need further clarification.

Thanks,
Sol

**Comment by jmcnamara** [comment]
Hi,

The results of a formula are intentionally set to zero if the formula result isn't specified by the user. The actual value is recalculated by Excel when the file load, for all version of Excel up to 2015 and probably later (I don't have Excel 365). From the [docs](https://metacpan.org/pod/distribution/Excel-Writer-XLSX/lib/Excel/Writer/XLSX.pm#Formula-Results): 


> **Formula Results**
>
>Excel::Writer::XLSX doesn't calculate the result of a formula and instead stores the value 0 as the formula result. It then sets a global flag in the XLSX file to say that all formulas and functions should be recalculated when the file is opened.
>
>This is the method recommended in the Excel documentation and in general it works fine with spreadsheet applications. However, applications that don't have a facility to calculate formulas will only display the 0 results. Examples of such applications are Excel Viewer, PDF Converters, and some mobile device applications.
>
>If required, it is also possible to specify the calculated result of the
formula using the optional last `value` parameter in `write_formula`:

    worksheet->write_formula('A1', '=2+2', num_format, 4);

**Comment by jmcnamara** [comment]
Ok. I see that you can't set the formula results as blank due to the `|| 0` in the code. I can change that so that you can set it to blank.

I'll need to verify that is valid first.

**Comment by soldemuth** [comment]
If you deem compliant with XLSX specs, this change would be quite helpful. Thanks!

**Comment by jmcnamara** [comment]
Fixed on master.
