### ISSUE TITLE
merge_range doesn't recognize dates

### ISSUE THREAD

**Issue by tlhackque** [jmcnamara/excel-writer-xlsx#229]
Unless I'm missing something, this probably amounts to a feature request for `merge_range_date_time`, but here's the detail:

The [doc for  `merge_range()`](https://metacpan.org/pod/Spreadsheet::WriteExcel#merge_range($first_row,-$first_col,-$last_row,-$last_col,-$token,-$format,-$utf_16_be)) says: 

> "merge_range() writes its $token argument using the worksheet write()
> method. Therefore it will handle numbers, strings, formulas or urls as
> required."

Which leaves out **dates**...

The following simple test case intends to merge 3 cells containing a date, formatted per [write_date_time](https://metacpan.org/pod/Spreadsheet::WriteExcel#write_date_time($row,-$col,-$date_string,-$format)) .  The cells are merged, but the date isn't recognized, and is formatted as a string.  

As shown, when written with `write_date_time` and (a copy of) the identical format, the date is formatted as expected.

If I also use `Excel::Writer::XLSX::Utility::xl_date_list` and manually parse the date_time, I can get the intended result.  But that function is [documented as "historical"](https://metacpan.org/pod/Excel::Writer::XLSX::Utility#TIME-AND-DATE-FUNCTIONS), and generating the date in two formats is inconvenient.

>  The date handling functions below are supplied for historical reasons. In
>    the current version of the module it is easier to just use the
>    "write_date_time()" function to write dates or times. See the DATES AND
>    TIME IN EXCEL section of the main Excel::Writer::XLSX documentation for
>    details.

What is the prefered method to create a merged cell range that is recognized as a date, starting with the ISO string that `Excel::Writer::XLSX` prefers elsewhere?  Is `merge_range_date_time` missing? (there seems to be a `merge_range_url`...)

Note: This is extracted from a larger script, which writes either .xlsx or .xls.  A common solution would be prefered.  

````Perl
#!/usr/bin/perl

use warnings;
use strict;

my $xclass = 'Excel::Writer::XLSX'; # 'Spreadsheet::WriteExcel'

eval "require $xclass; require ${xclass}::Utility; ${xclass}::Utility->import;";
die $@ if( $@ );

my $val = '2019-02-19T13:08:17.000';

my $wb = $xclass->new( 'foo.xls' . (substr( $xclass, -1, 1 ) eq 'X'? 'x': '' ) );
my $hfmt  = $wb->add_format( bold       => 1 );
my $ldfmt = $wb->add_format( num_format => 'ddd dd-mmm-yyyy hh:mm', align => 'left' );
my $xdfmt = $wb->add_format( num_format => 'ddd dd-mmm-yyyy hh:mm', align => 'left' );

my $ws = $wb->add_worksheet( 'Sheet' );

my $row = 5;

# Using write_date_time, can't merge
$ws->write_date_time( $row, 0, $val, $xdfmt );

# Using merg_range, not converted to a date
$ws->write_string( $row+1, 0, "Last notice", $hfmt );
$ws->merge_range( $row+1, 1, $row+1, 3, $val, $ldfmt );

# Manual conversion with xl_date_list
$ws->merge_range( $row+1, 5, $row+1, 7, xl_date_list( 2019, 2, 19, 13, 8, 17 ), $ldfmt );

$wb->close;
exit;

````
The test case creates `foo.xlsx` (or `foo.xls` if `$xclass` is changed).

Excel::Writer::XLSX 0.99, linux, Perl 5.8.8 (& newer).

**Comment by jmcnamara** [comment]
Hi,

Thanks for the detailed example.

There is an Excel::Writer::XLSX worksheet methods called [merge_range_type()](https://metacpan.org/pod/Excel::Writer::XLSX#merge_range_type(-$type,-$first_row,-$first_col,-$last_row,-$last_col,-...-)) which allows you to specify the type as `date_time` or whatever you need.

Note, that this is really just some syntactic sugar and you can get the same effect by using `merge_range()` with a default or empty string, and then overwriting the first cell in the range using whatever `write_()` method you want with the same format. Something like:

```perl
$worksheet->merge_range( 'B3:D4', 'Vertical and horizontal', $format );

$worksheet->write_date_time( 'B3', '2004-05-13T23:20', $format );
```

John

**Comment by tlhackque** [comment]
Thanks for the quick reply.  Not sure how I missed `merge_range_type`.

For anyone who, like me, has to generate both formats (.xls just won't die!):
* `merge_range_type` doesn't exist in `Spreadsheet::WriteExcel`
* `merge_range` followed by `write_date_time` works for `Excel::Writer::XLSX` but fails for `Spreadsheet::WriteExcel`

In the previous example, at line 24:

````Perl
$ws->merge_range( $row+1, 1, $row+1, 3, $val, $ldfmt ); # line 24: Unchanged
$ws->write_date_time( $row+1, 1, $val, $ldfmt );        # Add overwrite to convert time
````
This will work as suggested.

However, if you change the `$xclass` assignment on line 6 to be `my $xclass =  'Spreadsheet::WriteExcel';`
you get:
````
Error: refer to merge_range() in the documentation. Can't use previously merged format in non-merged cell at ./datealign line 25.
````
(Rather than a 'default' value, I just used the desired one.  Unsurpisingly, using '' doesn't fare any better.)

Thus, the suggestions are not backward-compatible.  It seems that if writing both formats is required, manually parsing the date and passing it to `xl_date_list` is the only viable option.

Given the status of  `Spreadsheet:WriteExcel`, we'll probably have to live with this.

Thanks, John, for all the work you've put into both modules for so long.
