### ISSUE TITLE
insert_image() does not scale on some images

### ISSUE THREAD

**Issue by ericllim** [jmcnamara/excel-writer-xlsx#233]
Hi John,

With the below script, using insert_image() to insert 3 images of the same size (95 x 84) results in 3 different scaled result.  Both image.xlsx and screen shot of this wrong behavior attached.

I've identified it to be a stray code in Excel/Writer/XLSX/Worksheet.pm and when I comment out these two lines, I get the desired result:

```diff
5670,5671c5670,5671
<     #$width  *= 96 / $x_dpi;
<     #$height *= 96 / $y_dpi;
---
>     $width  *= 96 / $x_dpi;
>     $height *= 96 / $y_dpi;
```

```perl
#!/usr/local/bin/perl 

use strict;
use warnings;
use Excel::Writer::XLSX;
 
my $workbook  = Excel::Writer::XLSX->new( 'image.xlsx' );
my $worksheet = $workbook->add_worksheet();
  
$worksheet->set_row( 9, 96.75 );
$worksheet->insert_image(9, 0, "85265_BKHP.jpg", 8.500,6.375,1,1);

$worksheet->set_row( 12, 96.75 );
$worksheet->insert_image(12, 0, "85265_NVPR.jpg", 8.500,6.375,1,1);

$worksheet->set_row( 15, 96.75 );
$worksheet->insert_image(15, 0, "65982_CDB.jpg", 8.500,6.375,1,1);
        
$workbook->close(); 
```

Version information:

```
    Perl version   : 5.028000
    OS name        : linux
    Module versions: (not all are required)
                     Excel::Writer::XLSX     	0.99
                     Spreadsheet::WriteExcel 	(not installed)
                     Archive::Zip            	1.64
                     XML::Writer             	(not installed)
                     IO::File                	1.39
                     File::Temp              	0.2304
```

![65982_CDB](https://user-images.githubusercontent.com/37705393/55350233-7525e980-5470-11e9-97e1-626063441d07.jpg)
![85265_BKHP](https://user-images.githubusercontent.com/37705393/55350249-7b1bca80-5470-11e9-8961-9cbcf6f49c2c.jpg)
![85265_NVPR](https://user-images.githubusercontent.com/37705393/55350250-7d7e2480-5470-11e9-92c4-dd70e2232ec8.jpg)
![Screen Shot 2019-04-01 at 11 16 22 AM](https://user-images.githubusercontent.com/37705393/55350257-81aa4200-5470-11e9-9ad3-233b1947992a.png)

[image.xlsx](https://github.com/jmcnamara/excel-writer-xlsx/files/3030793/image.xlsx)

**Comment by ericllim** [comment]
You are correct:

$ identify -format "%w x %h %x x %y" 85265_BKHP.jpg
95 x 84 72 PixelsPerInch x 72 PixelsPerInch

$ identify -format "%w x %h %x x %y" 85265_NVPR.jpg
95 x 84 72 Undefined x 72 Undefined

$ identify -format "%w x %h %x x %y" 65982_CDB.jpg
95 x 84 300 PixelsPerInch x 300 PixelsPerInch


Should the resolution matter though? All 3 images display the same on
the computer OS. But comes out different inside Excel. insert_image() should
follow the width and height, not the DPI.

The higher DPI just makes the image print clearer on other output devices that
outputs with higher DPI, but image size should be fixed at specified width and height.

DPI is only useful when you zoom. The higher DPI, the more you can zoom in.

**Comment by jmcnamara** [comment]
> Should the resolution matter though?

It matters to Excel, as demonstrated by the image above where the images inserted by Excel::Writer::XLSX as shown next to images inserted manually. 

Excel::Writer::XLSX emulates Excel's behaviour so if Excel takes the DPI into account, and it clearly does, then Excel::Writer::XLSX has to too.

Were you able to verify this behaviour in Excel?

**Comment by ericllim** [comment]
OK, I verified that you are mimicking the (odd) behavior of Excel and Word when
images are dropped from the OS or added using Insert Pictures.

One other issue is the 3 images dropped into Excel and Word show two sizes.
With Excel/Writer/XLSX, it shows three sizes. Please see attached.

> ('jpeg', 95, 84, '85265_NVPR.jpg', 96, 96)
> ...
> Note, the image with 96 DPI doesn't actually have any DPI in the file metadata
> so 96 is assumed by Excel::Writer::XLSX (and by Excel)

For the one without DPI info, you are defaulting to 96 but it seems like Excel and Word
are both defaulting DPI to 72.


Thanks!

**Comment by jmcnamara** [comment]
> Please see attached.

Github strips attachments when you reply via email.



> For the one without DPI info, you are defaulting to 96 but it seems like Excel and Word are both defaulting DPI to 72.

Not really. The image I posted above shows that Excel is also using 96dpi for the default image. The Excel::Writer::XLSX test suite also contains a lot of test cases using files created in Excel and they all match.

However, it may depend on the system DPI so some versions of Excel (particularly on the Mac) might behave differently, or the same version of Excel on different systems might behave differently if the default DPI is configured differently.

But for now 96 DPI matches the systems that I use for generating test file so that will remain the default.

Anyway, thanks for your input. I'll close this issue since there isn't anything to be fixed in Excel::Writer::XLSX

John
