### ISSUE TITLE
subtype percentage stacked is not working

### ISSUE THREAD

**Issue by kan-1** [jmcnamara/excel-writer-xlsx#235]
i tried using the subtype percentage stacked for the column chart but it is not working it would simply create a cloumn chart.

**Comment by jmcnamara** [comment]
Can you give a small, complete, working example that demonstrates the issue.

**Comment by jmcnamara** [comment]
It looks like it is working okay:

```perl
use Excel::Writer::XLSX;

my $workbook  = Excel::Writer::XLSX->new( 'percent_stacked.xlsx' );
my $worksheet = $workbook->add_worksheet();

my $chart = $workbook->add_chart(
    type     => 'column',
    subtype  => 'percent_stacked',
    embedded => 1
);

my $data = [
    [ 1, 2, 3, 4,  5 ],
    [ 2, 4, 6, 8,  10 ],
    [ 3, 6, 9, 12, 15 ],
];

$worksheet->write( 'A1', $data );

$chart->add_series( values => '=Sheet1!$A$1:$A$5' );
$chart->add_series( values => '=Sheet1!$B$1:$B$5' );
$chart->add_series( values => '=Sheet1!$C$1:$C$5' );

$worksheet->insert_chart( 'B7', $chart );

$workbook->close();

```

Output:

![screenshot](https://user-images.githubusercontent.com/94267/59981708-945f8d80-95ff-11e9-82b2-555188a28489.png)

**Comment by jmcnamara** [comment]
Any update on this?

**Comment by kan-1** [comment]
!/usr/bin/perl

use strict <https://metacpan.org/pod/strict>;
use warnings <https://metacpan.org/pod/warnings>;
use Excel::Writer::XLSX <https://metacpan.org/pod/Excel::Writer::XLSX>;

my $workbook  = Excel::Writer::XLSX->new( 'chart_column.xlsx' );
my $worksheet = $workbook->add_worksheet();
my $bold      = $workbook->add_format( bold => 1 );


my $headings = [ 'Number', 'Batch 1', 'Batch 2' ];
my $data = [
    [ 2, 3, 4, 5, 6, 7 ],
    [ 10, 40, 50, 20, 10, 50 ],
    [ 30, 60, 70, 50, 40, 30 ],

];

$worksheet->write( 'A1', $headings, $bold );
$worksheet->write( 'A2', $data );


my $chart = $workbook->add_chart( type => 'column', subtype
=>'percentage_stacked', embedded => 1 );


$chart->add_series(
    name       => '=Sheet1!$B$1',
    categories => '=Sheet1!$A$2:$A$7',
    values     => '=Sheet1!$B$2:$B$7',
);


$chart->add_series(
    name       => '=Sheet1!$C$1',
    categories => [ 'Sheet1', 1, 6, 0, 0 ],
    values     => [ 'Sheet1', 1, 6, 2, 2 ],
);


$chart->set_title ( name => 'Results of sample analysis' );
$chart->set_x_axis( name => 'Test number' );
$chart->set_y_axis( name => 'Sample length (mm)' );

$chart->set_style( 11 );
$worksheet->insert_chart( 'D2', $chart, 25, 10 );
The above code generates an excel sheet but on opening that excel sheet
Microsoft office shows an error saying " We found a problem with some
content in chart_column.xlsx. DO you want us to try to recover as much as
we can? If you trust the source of this workbook,click yes."

On clicking yes it wouldn't show the chart but excel sheet containing data
is generated fine.

**Comment by jmcnamara** [comment]
You have a typo in your code. It should be `percent_stacked` instead of `percentage_stacked`.

I ran your example (with that change and a close()) and it opened without issue:

```perl
#!/usr/bin/perl

use strict;
use warnings;
use Excel::Writer::XLSX;

my $workbook  = Excel::Writer::XLSX->new( 'chart_column.xlsx' );
my $worksheet = $workbook->add_worksheet();
my $bold      = $workbook->add_format( bold => 1 );


my $headings = [ 'Number', 'Batch 1', 'Batch 2' ];
my $data = [
    [ 2, 3, 4, 5, 6, 7 ],
    [ 10, 40, 50, 20, 10, 50 ],
    [ 30, 60, 70, 50, 40, 30 ],

];

$worksheet->write( 'A1', $headings, $bold );
$worksheet->write( 'A2', $data );


my $chart = $workbook->add_chart( type => 'column', subtype
=>'percent_stacked', embedded => 1 );


$chart->add_series(
    name       => '=Sheet1!$B$1',
    categories => '=Sheet1!$A$2:$A$7',
    values     => '=Sheet1!$B$2:$B$7',
);


$chart->add_series(
    name       => '=Sheet1!$C$1',
    categories => [ 'Sheet1', 1, 6, 0, 0 ],
    values     => [ 'Sheet1', 1, 6, 2, 2 ],
);


$chart->set_title ( name => 'Results of sample analysis' );
$chart->set_x_axis( name => 'Test number' );
$chart->set_y_axis( name => 'Sample length (mm)' );

$chart->set_style( 11 );
$worksheet->insert_chart( 'D2', $chart, 25, 10 );

$workbook->close();

```

Output:

![screenshot](https://user-images.githubusercontent.com/94267/60132764-15e82480-9794-11e9-897a-2855f22e3b3e.png)

**Comment by kan-1** [comment]
Sir,
With the changes that you suggested the excel sheet is opening fine but the
percent_stacked graph is still not made. The output chart is a normal
column chart
Regards
Kanishka

**Comment by jmcnamara** [comment]
- What version of Excel::Writer::XLSX are you using, and
- What version of Excel are you using?

**Comment by kan-1** [comment]
Ya i got it working thankyou very much!
Also the Metacpan site have this typo -percentage by percent
Regards
Kanishka

**Comment by kan-1** [comment]
Hey..!
Can you please help me with one more case.
I am creating an excel sheet and then converting the data to a chart...but
i want the chart only and delete the excel sheet which was created as an
intermediate step. Is there any way of doing it?
Thankyou
Kanishka

**Comment by jmcnamara** [comment]
> Ya i got it working thankyou very much!

Good. I'll close the issue.

> Also the Metacpan site have this typo -percentage by percent

I couldn't find it but if you could point it out that would be helpful.

 


> i want the chart only and delete the excel sheet which was created as an intermediate step. Is there any way of doing it?

No. As a workaround you could hide the worksheet with the data on it. https://metacpan.org/pod/Excel::Writer::XLSX#hide()

**Comment by kan-1** [comment]
Thabkyou so much for all you help.
Also can you please tell me why does add_table() function shows the error
"Can't locate object method "add_table" via package
"Excel::Writer::XLSX::Worksheet"

**Comment by jmcnamara** [comment]
> Also can you please tell me why does add_table() function shows the error

That usually means that you have an old version of E::W::X.
