### ISSUE TITLE
Can't read files created using Excel::Writer::XLSX when set_optimize is used

### ISSUE THREAD

**Issue by karlhamilton** [jmcnamara/excel-writer-xlsx#236]
I have a Perl script that creates a workbook using Excel::Writer::XLSX.  We were having issues running out of memory on our server and were testing the set_optimize setting.

The problem is that I can't read the xlsx files create with set_optimize on with my Perl script.  The only change to the script was turning set_optimized on.  However, it looks fine in Excel.

The script has a subroutine that reads the previous xlsx file and uses data from that sheet in the history sheet of the new workbook.

I'm only getting one row in the history sheet from previous executions and only the first column of that.  The subroutine used to read the xlsx files is attached.

[convert_history_file.txt](https://github.com/jmcnamara/excel-writer-xlsx/files/3387387/convert_history_file.txt)

**Comment by jmcnamara** [comment]
If you open the file with Excel does it have all the data you would expect?

**Comment by karlhamilton** [comment]
Yes, it looks fine in Excel.  I did notice a few differences in the xml files, but not sure if it's related.   The new file no longer has sharedStrings.xml

**Comment by jmcnamara** [comment]
> The new file no longer has sharedStrings.xml

Yes. That is one of the optimizations to reduce the memory overhead. The strings are written inline in the worksheet files. 

This is a valid part of the file format and as you can see from your check Excel supports it. 

However, it looks like the module you are using to read the file doesn’t.

**Comment by jmcnamara** [comment]
Closing since this doesn't look like an Excel::Writer::XLSX issue.
