### ISSUE TITLE
Table formatting. A bug or a feature?

### ISSUE THREAD

**Issue by pmqs** [jmcnamara/excel-writer-xlsx#242]
I'm attempting to set some numeric formatting on a table but its doesn't work as expected.

The code below creates two tables. The only difference between them is one uses `add_table` to both create the table AND insert the data into the cells. The other fills out the data in the cells first, then it creates the table.

The first works as expected -- the formatting is applied. 

![image](https://user-images.githubusercontent.com/2691108/65338502-3c1a3680-dbc2-11e9-9b96-f476613a7029.png)

The seconds one does not apply formatting. 

![image](https://user-images.githubusercontent.com/2691108/65338546-56541480-dbc2-11e9-83d5-cdf8cc933afc.png)

Bug or feature?

### Test Code

```perl
#!/usr/bin/perl

use strict;
use warnings;
use Excel::Writer::XLSX;

my $workbook    = Excel::Writer::XLSX->new( '/tmp/tables.xlsx' );
my $worksheet1 = $workbook->add_worksheet();
my $worksheet2 = $workbook->add_worksheet();

my $currency_format = $workbook->add_format( num_format => '$#,##0' );


# Some sample data for the table.
my $data = [
    [ 'Apples',  10000, 5000, 8000, 6000 ],
    [ 'Pears',   2000,  3000, 4000, 5000 ],
    [ 'Bananas', 6000,  6000, 6500, 6000 ],
    [ 'Oranges', 500,   300,  200,  700 ],

  ];



my @columns =  (
            { header => 'Product', total_string => 'Totals' },
            {
                header         => 'Quarter 1',
                total_function => 'sum',
                format         => $currency_format,
            },
            {
                header         => 'Quarter 2',
                total_function => 'sum',
                format         => $currency_format,
            },
            {
                header         => 'Quarter 3',
                total_function => 'sum',
                format         => $currency_format,
            },
            {
                header         => 'Quarter 4',
                total_function => 'sum',
                format         => $currency_format,
            },
        );


# Sheet 1
# =======

# Add a table to the worksheet.
$worksheet1->add_table(0, 0, 4, 4,
    {
        data      => $data,
        total_row => 1,
        columns   => \@columns,
    }
);

# Sheet 2
# =======
my $ix = 0 ;
for my $r (@$data)
{
    ++ $ix ;
    $worksheet2->write($ix, 0, $r );
}

# Add a table to the worksheet.
$worksheet2->add_table(0, 0, 4, 4,
    {
        total_row => 1,
        columns   => \@columns,
    }
);

$workbook->close();
```

### System Details

```
    Perl version   : 5.016003
    OS name        : linux
    Module versions: (not all are required)
                     Excel::Writer::XLSX     	1.00
                     Spreadsheet::WriteExcel 	(not installed)
                     Archive::Zip            	1.30
                     XML::Writer             	(not installed)
                     IO::File                	1.16
                     File::Temp              	0.2301
```

**Comment by jmcnamara** [comment]
Thanks for he detailed bug report.

It is probably more of a feature than a bug. When you use `add_table()` with column formats and data the method applies the format to the data when writing it. When you write the data yourself the formatting doesn't automagically get applied.

You can workaround this by applying the format when you write the data externally to `add_table()`:

```perl
# Sheet 2
# =======
my $ix = 0 ;
for my $r (@$data)
{
    ++ $ix ;
    $worksheet2->write($ix, 0, $r, $currency_format );
}
```

**Comment by jmcnamara** [comment]
P.S., I see that you are the author of zipdetails (and we communicated in the past about zip modules). I have an issue with the Python version of Excel::Writer::XLSX where a ZIP64 file is corrupted (and zipdetails reports an `Unexpecded END`). Would you interested in having a look to see if you can spot the zip issue.

**Comment by pmqs** [comment]
...
> You can workaround this by applying the format when you write the data externally to `add_table()`:
> ```

Thanks. I'm _sure_ I tried that approach with the real application and couldn't get it to work. Leave that with me & I'll see if I'm deluding myself with a false memory :-)

**Comment by pmqs** [comment]
> P.S., I see that you are the author of zipdetails (and we communicated in the past about zip modules). I have an issue with the Python version of Excel::Writer::XLSX where a ZIP64 file is corrupted (and zipdetails reports an `Unexpecded END`). Would you interested in having a look to see if you can spot the zip issue.

Sure, no problem. Is it this issue https://github.com/jmcnamara/XlsxWriter/issues/656?

**Comment by jmcnamara** [comment]
> Sure, no problem. Is it this issue ...

Yes. Thanks. I'll hook you in over there.
