### ISSUE TITLE
conditional_format + num_format

### ISSUE THREAD

**Issue by TimurDela** [jmcnamara/excel-writer-xlsx#244]
would it be possible to add the 'format' parameter to '2_color_scale' so it is possible to at least set num_format?

Thanks

**Comment by jmcnamara** [comment]
> would it be possible to add the 'format' parameter to '2_color_scale'

As far as I know that isn't possible in Excel. You can only change the colors in a 2 Color Scale. You can verify that yourself.



> is possible to at least set num_format?

You can set the number format for the cells using `write()` and then put a conditional format over them. That is how you would do it in Excel. Would that work for you?

**Comment by jmcnamara** [comment]
No feedback. Closing
