### ISSUE TITLE
Is faster ->_store_workbook() perfomance possible via a different Archive library?

### ISSUE THREAD

**Issue by GH-A-CC** [jmcnamara/excel-writer-xlsx#251]
I'm using this great library to generate XLSX files based on a processed XML input. In brief, for each XML file input I need to generate somewhere between 1000 and 8000 output files. 

When profiling the code I'm using, the Archive::Zip dependency in Excel::Writer::XLSX is responsible for a large fraction of the execution time vs. the rest of the Excel::Writer::XLSX cost.  In test cases I found that consistently the calls to Archive::Zip::Archive::writeToFileHandle()  are  responsible for ~45% of the time within the _store_workbook() sub, which itself (in my use-case) accounts for over 85% of the CPU time involved with  Excel::Writer::XLSX overall.

I was interested to know if this could be sped up somewhat - perhaps by using another library, such as IO::Compress::Zip - have you done any tests in this regard?  Or is this about as fast as it can get short of my doing a redesigned approach (e.g. multi-threading).

**Comment by jmcnamara** [comment]
I'm not aware of any faster zipping method. @pmqs might know.

Alternatively, you could try the C version which is ~10x faster: https://github.com/jmcnamara/libxlsxwriter

**Comment by pmqs** [comment]
Behind the scenes both `Archive::Zip` and` IO::Compress::Zip`  use the module `Compress::Raw::Zlib` to do the hard work of compression. 

The true source of the bottleneck is either going to be  `Compress::Raw::Zlib` or file IO (or a bit of both). I suspect the former.

@GH-A-CC:  When you did your analysis did anything in `Compress::Raw::Zlib` show up? 

Possible alternatives to speed things up.

1. Use the commandline zip to create the xlsx file. 
It's very likely that that would be quicker than using the native perl modules. Portability of `Excel::Writer::XLSX` to platforms that don't have a commandline zip would be an issue.

1. libarchive
An alternative, which I've never tried, is `libarchive`. There are Perl bindings for it, but I've no idea if it will make any difference to performance.

**Comment by jmcnamara** [comment]
Closing since this is more of a question than a bug report.
