### ISSUE TITLE
Feature: improve example code to allow direct paste in custom solution

### ISSUE THREAD

**Issue by mi-hol** [jmcnamara/excel-writer-xlsx#252]
The examples are great but have hard coded ranges that will only work for the given data.
For example excel-writer-xlsx/examples/autofilter.pl has a hard coded range of 'A1:D51'

To promote good coding practices and allow direct copy&paste of code, how about adding a function that handles ranges in a flexible but consistent way?

PS: I'd love to contribute such a solution but my PERL knowledge is very limited at this time and I've started to maintain a very old & ugly code base only now

**Comment by jmcnamara** [comment]
> The examples are great but have hard coded ranges that will only work for the given data.
> For example excel-writer-xlsx/examples/autofilter.pl has a hard coded range of 'A1:D51

All of the APIs in Excel::Writer::XLSX provide row-column notation as well as A1 range styles. From the [docs on autofilter()](https://metacpan.org/pod/Excel::Writer::XLSX#autofilter(-$first_row,-$first_col,-$last_row,-$last_col-)):

> To add an autofilter to a worksheet:
```perl
$worksheet->autofilter( 0, 0, 10, 3 );
$worksheet->autofilter( 'A1:D11' );    # Same as above in A1 notation.
```



See also the section of [Cell Notation](https://metacpan.org/pod/Excel::Writer::XLSX#Cell-notation):

> Excel::Writer::XLSX supports two forms of notation to designate the position of cells: Row-column notation and A1 notation.

> Row-column notation uses a zero based index for both row and column while A1 notation uses the standard Excel alphanumeric sequence of column letter and 1-based row. For example:
```perl
(0, 0)      # The top left cell in row-column notation.
('A1')      # The top left cell in A1 notation.
 
(1999, 29)  # Row-column notation.
('AD2000')  # The same cell in A1 notation.
```
> Row-column notation is useful if you are referring to cells programmatically:

```perl
for my $i ( 0 .. 9 ) {
    $worksheet->write( $i, 0, 'Hello' );    # Cells A1 to A10
}
```

> A1 notation is useful for setting up a worksheet manually and for working with formulas:

```perl
$worksheet->write( 'H1', 200 );
$worksheet->write( 'H2', '=H1+1' );
```

Most of the example programs use A1 notation since it is visually clearer for examples or docs.
