### ISSUE TITLE
Unable to set font color for text

### ISSUE THREAD

**Issue by rfulbrig** [jmcnamara/excel-writer-xlsx#253]
When I run the code below I get the error message "Unknown method: Excel::Writer::XLSX::Format::set_font_color".

I am running Strawberry Perl 5.24.1 on Windows 10 and module version 1.03.

#!/usr/bin/perl
use strict;
use warnings;
use Excel::Writer::XLSX;

my $workbook = Excel::Writer::XLSX->new( 'test.xlsx' );
my $worksheet = $workbook->add_worksheet("Sheet1");
my $format = $workbook->add_format();

$format->set_font_color( 'red' );
$worksheet->write( 'A1', 'test' );
$workbook->close() if defined $workbook;

**Comment by jmcnamara** [comment]
The method you are looking for is `set_color()`: https://metacpan.org/pod/Excel::Writer::XLSX#set_color()

**Comment by rfulbrig** [comment]
Thank you, John.  Works fine now.  And thank you for this marvelous module!  I have found so many uses for it (home, work, church, etc).  It might be helpful to remove "set_font_color()" from the docs.  Thanks again.

Best regards,
Roy

________________________________

**Comment by jmcnamara** [comment]
> It might be helpful to remove "set_font_color()" from the docs.

Thanks. Done.
