### ISSUE TITLE
Use a text template to define a worksheet [feature request]

### ISSUE THREAD

**Issue by tbrowder** [jmcnamara/excel-writer-xlsx#254]
I have a need to generate multiple workbooks, one worksheet per workbook, from 
a template, and am designing my own format for that purpose. I will use the Raku language to parse the text-file template, then, with the aid of the Raku module 'Inline::Perl5',
I will read my xslx data files with one of the Perl xslx readers and then use this module to
write new, filtered files in the form of the template.

Would some similar thing be useful as a built-in feature of this module?

I am just starting but I'm looking at a template format something like this, one line per row, cells separated by pipes ('|'), key/value attribute pairs following the cell content:

    # This is a comment. The following row describes one xslx row with four columns, the
    # first column being empty, and it has an ending comment.
    # Comments to eol are stripped before parsing the row.
    | some text | 5.26 | ="some formula" :color(red) :width(2) # comment...
    # another comment and more rows following

    # empty rows are ignored, the worksheet will have all rows padded with empty cells
    # to the maximum number of cells found on any row
    |  # this is a row with two empty cells

**Comment by tbrowder** [comment]
I have started such a project on Github. See [Raku module `Excel`](https://github.com/tbrowder/Excel-Raku).

**Comment by jmcnamara** [comment]
Hi Tom,

That looks interesting. Let me know how you get on and I can add a link to it in the docs when it is functional.

John

**Comment by tbrowder** [comment]
On Wed, Apr 15, 2020 at 18:34 John McNamara <notifications@github.com>
wrote:

> Hi Tom,
>
> That looks interesting. Let me know how you get on and I can add a link to
> it in the docs when it is functional.
>

Thanks, John, will do!

Blessings,

-Tom
