### ISSUE TITLE
Creating chart on tab named with spaces

### ISSUE THREAD

**Issue by brantfagan** [jmcnamara/excel-writer-xlsx#256]
Strawberry Perl 5.30.2.1
Excel::Writer::XLSX 1.03

When I create a bar chart on a worksheet that is named using spaces, the chart shows up but the value bars and the axis categories are not drawn. Removing the spaces in the tab name and the worksheet reference in the chart parameters solves the problem. Below is a code snip that illustrates the problem.

        my $lms_to_ddw_worksheet = $workbook->add_worksheet('LMS to DDW');
        $lms_to_ddw_worksheet->set_tab_color('yellow');
        $lms_to_ddw_worksheet->write_string('A1','Row Labels',$bold_black_on_light_blue);
        $lms_to_ddw_worksheet->write_string('A2','MatchMatchMatch');
        $lms_to_ddw_worksheet->write_string('A3','Grand Total',$bold_black_on_light_blue);
        $lms_to_ddw_worksheet->write_string('B1','Count of DOSNUM',$bold_black_on_light_blue);
        my $lms_to_ddw_mmm_formula = '=COUNTIF(TR!$O$1:$O$' . ($amort_tr_rowcnt + 1) . ',"MatchMatchMatch")';
        $lms_to_ddw_worksheet->write_formula(1,1,$lms_to_ddw_mmm_formula);
        $lms_to_ddw_worksheet->write_number('B3',$amort_tr_rowcnt,$bold_black_on_light_blue);

        # Add chart
        my $amort_lms_to_ddw_chart = $workbook->add_chart('type'=>'column','name'=>'Results Chart','embedded'=>1);
        $amort_lms_to_ddw_chart->add_series(
            'name'=>'LMS to DDW',
            'data_labels'=>{'legend_key'=>1},
            'categories'=>'=LMS to DDW!$A$2:$A$2',
            'values'=>'=LMS to DDW!$B$2:$B$2'
        );
        $lms_to_ddw_worksheet->insert_chart('D2',$amort_lms_to_ddw_chart);

**Comment by jmcnamara** [comment]
Short answer: In Excel you need to single quote sheet names when they contain spaces (and some special characters. Like this (using q() to avoid escapes):

    q(=‘LMS to DDW’!$A$2:$A$2)

I’ll post a slightly longer answer when I’m online.

**Comment by jmcnamara** [comment]
Slightly longer answer from the [docs](https://metacpan.org/pod/Excel::Writer::XLSX::Chart):

> The categories and values can take either a range formula such as =Sheet1!$A$2:$A$7 or, more usefully when generating the range programmatically, an array ref with zero indexed row/column values:
>
>```perl
>      [ $sheetname, $row_start, $row_end, $col_start, $col_end ]
>```
>The following are equivalent:
>
>```perl
>    $chart->add_series( categories => '=Sheet1!$A$2:$A$7'      ); # Same as ...
>    $chart->add_series( categories => [ 'Sheet1', 1, 6, 0, 0 ] ); # Zero-indexed.
>```

Using the second aref method will handle sheet name quoting auotmatically.
