### ISSUE TITLE
Recommend Spreadsheet::ParseXLSX as reader

### ISSUE THREAD

**Issue by tbrowder** [jmcnamara/excel-writer-xlsx#257]
I have been searching for the XLSX reader that can give me the most information in my quest for a reader/writer combo for my Raku project. So far it looks like "Spreadsheet::ParseXLSX" is the one I will use because it can access formulas (and much more) in its current version.

I do not see it suggested in your list of XLSX readers, but I think it should be.

**Comment by jmcnamara** [comment]
I'm not sure why that isn't there.

If you like you can update your open PR and add a link to that module in the docs.

**Comment by tbrowder** [comment]
>
> If you like you can update your open PR and add a link to that module in
> the docs.
>
Will do, John! Thanks.

>

**Comment by jmcnamara** [comment]
Marged in #255. Closing.
