### ISSUE TITLE
Unexpected Hex conversion with Text format 

### ISSUE THREAD

**Issue by swarmhawk** [jmcnamara/excel-writer-xlsx#258]
I looked through documentation and both open and closed issues and didn't see this discussed, so I'm not sure this behavior is expected or not.

I am attempting to convert tab delimited hex numbers to Excel file using text format and keep leading zeros.  Values with "E" are being interpreted as scientific notation number instead of text.  

The program is based on the idiomatic conversion example in the Excel::Writer::XLSX documentation:

![Tab2XLSX](https://user-images.githubusercontent.com/66127862/83284896-fc6d0b00-a1a2-11ea-90ee-dc584a306a37.PNG)

[TabtoXLSX.txt](https://github.com/jmcnamara/excel-writer-xlsx/files/4703197/TabtoXLSX.txt)

Input file.txt:
![file](https://user-images.githubusercontent.com/66127862/83285589-1bb86800-a1a4-11ea-9b18-0ba3df466b43.PNG)

[file.txt](https://github.com/jmcnamara/excel-writer-xlsx/files/4703105/file.txt)

Results in expected text results in top line, but scientific numbers in the bottom line:
![filexlsx](https://user-images.githubusercontent.com/66127862/83285836-94b7bf80-a1a4-11ea-9e2c-5dbe620e42b7.PNG)

The same thing happens when using Spreadsheet::WriteExcel as well.  Is there another way I should be dealing with this conversion?

**Comment by jmcnamara** [comment]
Excel::Writer::XLSX is just (more of less) copying perl's handling of strings that look like numbers:

```
$ perl -le 'print 0 + "2E25"'
2e+25
```

The `write()` method is just some syntactic sugar. It tries to do the right thing but in the absence of type information it doesn't always get it right.

The best thing to do is to avoid using it in cases like this where it doesn't do what you want and instead use a more explicit method such as `write_string()` or `write_number()`.
