### ISSUE TITLE
Is it possible to move/reorder sheets?

### ISSUE THREAD

**Issue by bandtank** [jmcnamara/excel-writer-xlsx#262]
I am looking for a way to move sheets after instantiation, but I haven't seen anything in the docs about this particular topic. It's entirely possibly I've simply overlooked it. For now, I'm managing my particular situation by copying the example [here](https://metacpan.org/pod/Excel::Writer::XLSX::Examples#Example:-hide_sheet.pl), which is working well enough. It would be great to be able to move a sheet, though.

I am aware of `activate()` and `set_first_sheet()`, but those behave differently than what I am seeking to do. I want my sheets to go from `A B C` to `B C A`.

In case it helps, the `workbook.xml` file shows sheet IDs, which I would imagine are changeable, but maybe not:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook ...>
    <fileVersion .../>
    <workbookPr .../>
    <bookViews>
        ...
    </bookViews>
    <sheets>
        <sheet name="Config" sheetId="1" r:id="rId1"/>
        <sheet name="AA" sheetId="2" r:id="rId2"/>
        <sheet name="BB" sheetId="3" r:id="rId3"/>
        <sheet name="CC" sheetId="4" r:id="rId4"/>
        <sheet name="DD" sheetId="5" r:id="rId5"/>
        <sheet name="EE" sheetId="6" r:id="rId6"/>
        <sheet name="MM" sheetId="7" r:id="rId7"/>
    </sheets>
    <calcPr .../>
</workbook>
```

In the example shown above, I want `Config` to be listed at the end instead of the beginning. Unfortunately, I have to create the sheet first because the other sheets use it.

**Comment by jmcnamara** [comment]
Apologies. Somehow I missed this issue.

> I am looking for a way to move sheets after instantiation,

Unfortunately, that isn't possible. Excel::Writer::XLSX uses an internal indexing for the worksheets based on the order of creation.
