### ISSUE TITLE
Could you add a 'flush' method to write any data to file?

### ISSUE THREAD

**Issue by DavidAyliffe** [jmcnamara/excel-writer-xlsx#268]
Calling "write..." doesn't result in the data being written to the file.

Could you fix this by adding a "flush()" method?

The alternative is to open and close the file each time but this is not as clean as desirable.

Thanks
DA

**Comment by jmcnamara** [comment]
> Calling "write..." doesn't result in the data being written to the file. Could you fix this by adding a "flush()" method?

Unfortunately not. An xlsx file is actually a zip container containing a number of linked xml files. So the file can't be written, or flushed, until the entire file is written.
