### ISSUE TITLE
Warning on uninitialized value.

### ISSUE THREAD

**Issue by shenyush** [jmcnamara/excel-writer-xlsx#270]
I am getting 

Use of uninitialized value $_[2] in addition (+) at /usr/share/perl5/vendor_perl/5.32/Excel/Writer/XLSX/Worksheet.pm line 2308.

Original code
my $num = $_[2] + 0;

My workaround was
my $num  = $_[2];
$num += 0;

Thanks

**Comment by jmcnamara** [comment]
Thanks.

How did you generate that warning? With something like this:

```perl
$worksheet->write_number( 0, 0, undef );
```

**Comment by shenyush** [comment]
Yes, that’s what I was doing, apparently the variable was null. Now I am not sure if this should be considered a bug or else.

Thanks.

**Comment by jmcnamara** [comment]
> Now I am not sure if this should be considered a bug or else.

It is probably more in the input error than bug category. It isn't intended that undef is treated implicitly as the number 0.

So for now may just put a check in your code to unsure that undef doesn't get passed to write_number().
