### ISSUE TITLE
Metacpan "homepage" link is incorrect

### ISSUE THREAD

**Issue by whosgonna** [jmcnamara/excel-writer-xlsx#272]
On metacpan, the "Homepage" link points to:

http://jmcnamara.github.com/excel-writer-xlsx/

It should point to:

https://github.com/jmcnamara/excel-writer-xlsx

**Comment by jmcnamara** [comment]
Thanks. That is fixed on main (and reported in #269) but I haven't pushed an update since the fix. I may do one in the next few weeks.
