### ISSUE TITLE
Reporting a Bug in Excel::Writer::XLSX

### ISSUE THREAD

**Issue by jmcnamara** [jmcnamara/excel-writer-xlsx#29]
Feel free to report bugs in Excel::Writer::XLSX but to save time consider the following steps first.

**Upgrade to the latest version of the module**

The bug you are reporting may already be fixed in the [latest version](http://search.cpan.org/~jmcnamara/Excel-Writer-XLSX/).

**Read the documentation**

The [Excel::Writer::XLSX documentation](http://search.cpan.org/~jmcnamara/Excel-Writer-XLSX/lib/Excel/Writer/XLSX.pm) has been refined in response to user questions. Therefore, if you have a question it is possible that someone else has asked it before you and that it is already addressed in the documentation.

Since there is a lot of documentation to get through you should at least look at the [table of contents](http://search.cpan.org/~jmcnamara/Excel-Writer-XLSX/lib/Excel/Writer/XLSX.pm), search for keywords and check the [known bugs](http://search.cpan.org/~jmcnamara/Excel-Writer-XLSX/lib/Excel/Writer/XLSX.pm#BUGS) and [limitations](http://search.cpan.org/~jmcnamara/Excel-Writer-XLSX/lib/Excel/Writer/XLSX.pm#LIMITATIONS).

**Look at the example programs**

[There are over 75 example programs](http://search.cpan.org/~jmcnamara/Excel-Writer-XLSX/lib/Excel/Writer/XLSX/Examples.pm) shipped with the standard Excel::Writer::XLSX distribution. Many of these were created in response to user questions. Try to identify an example program that corresponds to your query and adapt it to your needs.

**If you submit a bug report here are some pointers**
1.  Describe the problem as clearly and as concisely as possible.
2.  Include a sample program. This is probably the most important step. Also, it is often easier to describe a problem in code than in written prose.
3.  The sample program should be as small as possible to demonstrate the problem. Don't copy and past large sections of your program. The program should also be self contained and working.

A sample bug report is shown below. If you use this format then it will help to analyse your question and respond to it more quickly.

> I am using Excel::Writer::XLSX and I have encountered a problem. I want it to do SOMETHING but the module appears to do SOMETHING_ELSE.
> 
> Here is some code that demonstrates the problem.

```
#!/usr/bin/perl -w

use strict;
use Excel::Writer::XLSX;

my $workbook  = Excel::Writer::XLSX->new("reload.xls");
my $worksheet = $workbook->add_worksheet();

$worksheet->write(0, 0, "Hi Excel!");

__END__
```

> My automatically generated system details are as follows (include the output from this program):

```
use strict;
use warnings;

print "\nPerl version   : $]";
print "\nOS name        : $^O";
print "\nModule versions: (not all are required)\n";

my @modules = qw(
                  Excel::Writer::XLSX
                  Spreadsheet::WriteExcel
                  Archive::Zip
                  XML::Writer
                  IO::File
                  File::Temp
                );


for my $module (@modules) {
    my $version;
    eval "require $module";

    if (not $@) {
        $version = $module->VERSION;
        $version = '(unknown)' if not defined $version;
    }
    else {
        $version = '(not installed)';
    }

    printf "%17s%-24s\t%s\n", "", $module, $version;
}

__END__
```

**Comment by NicoHood** [comment]
You can also add a `CONTRIBUTING.md` file with this information and on any new Github issue a warning will pop up. I think this catches more attention than an old "issue" with the lable "Read this first".

Example:
https://github.com/arduino/arduino-builder/issues/new

**Comment by jmcnamara** [comment]
@NicoHood 

There is [one](https://github.com/jmcnamara/excel-writer-xlsx/blob/master/CONTRIBUTING.md). :-)

You would be surprised by how many people don't read that or (the Read this first for that matter).

**Comment by NicoHood** [comment]
Oh. I missed that. How embarrassing, sorry.
Yeah I was just looking through the issues to maybe find an issue about some features and found this issue then. Nevermind ;)
