### ISSUE TITLE
Support Adjacent columns with the same outline level in different groups

### ISSUE THREAD

**Issue by josiah47** [jmcnamara/excel-writer-xlsx#290]
The documentation currently says "Adjacent columns with the same outline level are grouped together into a single outline."
Is it possible to support adjacent column groupings? 
We had pulled this off with the ODF::lpOD library but are switching to your library and it seems to not be possible, it also is possible to manually create this in libreoffice calc; I don't know if excel actually supports this scenario.
I tried to set collapsed => 1 to indicate starting a new outline level group. but it just forces all the columns into one group.
I have seen others with screenshots that they have inserted a blank column between two columns to get past this. I would like to avoid that.
### Suggested support
``` perl
$worksheet6->set_column( 'H:H', 5,  $format, 0, 1, 1 ); # start a new grouping at level 1
$worksheet6->set_column( 'I:I', 10, $format, 0, 1 );
$worksheet6->set_column( 'J:J', 15, $format, 0, 1 );
$worksheet6->set_column( 'K:K', 20, $format, 0, 1 );
$worksheet6->set_column( 'L:L', 10, $format, 0, 1 );
$worksheet6->set_column( 'M:M', 10, $format, 0, 1 );
$worksheet6->set_column( 'N:N', 10, $format, 0, 1 );
$worksheet6->set_column( 'O:O', 5, $format, 0, 1, 1 ); # start another new grouping at level 1
$worksheet6->set_column( 'P:P', 10, $format, 0, 1 );
```

![Screenshot_2023-10-07_10-49-49](https://github.com/jmcnamara/excel-writer-xlsx/assets/870875/63e61e79-66aa-429e-9227-968572afa669)

**Comment by jmcnamara** [comment]
> I don't know if excel actually supports this scenario.

This is probably the important part. I don't think Excel allows this if which case it can't be supported by Excel::Writer::XLSX.

So it is best to check in Excel first. If it can be done then there is probably some way to do it with Excel::Writer::XLSX.

**Comment by josiah47** [comment]
Confirmed in excel 2012. it does not support this and create one group.
Also confirmed online via searching that the only way to pull this off in excel is to insert a blank column.
I even tried opening a ODS file that supported this in Calc and it made it one group in excel.
Thanks for your help.
