### ISSUE TITLE
Feature Request: Use slicers to filter data

### ISSUE THREAD

**Issue by matthias-reissner** [jmcnamara/excel-writer-xlsx#291]
To create Excel dashboards using this perl module please add the feature to add slicers to tables to filter data using buttons

See https://support.microsoft.com/en-us/office/use-slicers-to-filter-data-249f966b-a9d5-4b0f-b31a-12651785d29d

**Comment by jmcnamara** [comment]
The best thing to do is to add this as a +1 request to the similar Python feature request. If it gets implemented it will be implemented in the Perl and Python versions at the same time.

https://github.com/jmcnamara/XlsxWriter/issues/918
