### ISSUE TITLE
write_formula with image puts @ in front of formula

### ISSUE THREAD

**Issue by srchulo** [jmcnamara/excel-writer-xlsx#293]
When I use the write_formula subroutine:

`$worksheet->write_formula($row, $column, "=IMAGE($url)", $cell_format);`

It goes into the sheet like this:

`=@IMAGE($url)`

And causes an error. The @ doesn't get inserted with other functions, like SUM. It then gives the error: `#NAME?`:

![image](https://github.com/jmcnamara/excel-writer-xlsx/assets/935847/ac6f6ba3-dfc0-4ef0-8027-3e0cd44fc1dd)

**Comment by srchulo** [comment]
Actually, using _xlfn.image seemed to solve this...weird. Found here:

https://techcommunity.microsoft.com/t5/excel/image-function-adding-implicit-intersection-at-operator-image/m-p/3804842/highlight/true#M189438

**Comment by jmcnamara** [comment]
> Actually, using _xlfn.image seemed to solve this

That is the correct fix. The reason is explained in the docs: https://metacpan.org/pod/Excel::Writer::XLSX#Formulas-added-in-Excel-2010-and-later

The library usually adds the extension automatically but `IMAGE()` is relatively new and I haven't added it to the automatic handling. I'll add that to the next release.

**Comment by srchulo** [comment]
ah, sorry I missed that. Thanks for the pointer!

**Comment by jmcnamara** [comment]
> ah, sorry I missed that.

No worries. It isn't obvious. I've fixed the docs and internal handling of `IMAGE()` on main. However the handling isn't automatic, like I thought, for performance reasons. So you will need to enable the automatic conversion like this:

```perl
use strict;
use Excel::Writer::XLSX;

my $workbook  = Excel::Writer::XLSX->new( 'image.xlsx' );
my $worksheet = $workbook->add_worksheet();

$worksheet->{_use_future_functions} = 1;

$worksheet->write( 1, 1, '=IMAGE("https://support.content.office.net/en-us/media/2d9e717a-0077-438f-8e5e-f85a1305d4ad.jpg", "Sphere")' );

$workbook->close();
```

Output:

![screenshot](https://github.com/jmcnamara/excel-writer-xlsx/assets/94267/6c8e0bec-02bf-4ad1-9add-cf6078622491)
