### ISSUE TITLE
Out-dated FSF address

### ISSUE THREAD

**Issue by ppisar** [jmcnamara/excel-writer-xlsx#295]
LICENSE_GPL_1.0 quotes a Free Software Foundation's postal address. That address is not valid anymore. Please consider updating the wording from <https://www.gnu.org/licenses/old-licenses/gpl-1.0.txt> to provide an up-to-date address to your users.

**Comment by jmcnamara** [comment]
The version in the repo is the version from the Perl webpage on licensing:

https://dev.perl.org/licenses/
https://dev.perl.org/licenses/gpl1.html
