### ISSUE TITLE
Argument isn't numeric when a hex colour is used

### ISSUE THREAD

**Issue by realflash** [jmcnamara/excel-writer-xlsx#300]
v1.12 under perl 5.38 on Windows

I am trying to use [Spreadsheet::ParseXLSX](https://metacpan.org/pod/Spreadsheet::ParseXLSX), [Excel::CloneXLSX::Format](https://metacpan.org/pod/Excel::CloneXLSX::Format) and [Excel::Writer::XLSX](https://metacpan.org/pod/Excel::Writer::XLSX). When I run the sample code in the [SYNOPSIS](https://metacpan.org/pod/Excel::CloneXLSX::Format#SYNOPSIS) of Excel::CloneXLSX::Format I get this error:
`Argument "#4F81BD" isn't numeric in numeric ne (!=) at C:/Users/<username>/dev//dist/perl/perl/site/lib/Excel/Writer/XLSX/Package/Styles.pm line 797`

The sample XLSX that comes with this module does indeed set a border colour with this colour in it. In the documentation for Excel::Writer::XLSX, [set_color()](https://metacpan.org/pod/Excel::Writer::XLSX#set_color()) suggests that only integers and colour names are accepted (although it is unclear what these integers are supposed to represent). In [WORKING WITH COLOURS](https://metacpan.org/pod/Excel::Writer::XLSX#WORKING-WITH-COLOURS) it says that a hex value can be used throughout. The line in question looks like this:

```
sub _write_sub_border {

    my $self  = shift;
    my $type  = shift;
   
   ... (chopped some stuff out) ...
   

    if ( $color && $color != 64 ) {
        $color = $self->_get_palette_color( $color );

        $self->xml_empty_tag( 'color', 'rgb' => $color );
    }
    else {
        $self->xml_empty_tag( 'color', 'auto' => 1 );
    }

    $self->xml_end_tag( $type );
}
```

Which indeed would not support a hex colour. So at first glance it looks like this was forgotten when support for hex values was added? I would be happy to supply a PR if you could explain what 64 is and why it is being tested for.

**Comment by jmcnamara** [comment]
> When I run the sample code in the [SYNOPSIS](https://metacpan.org/pod/Excel::CloneXLSX::Format#SYNOPSIS) of Excel::CloneXLSX::Format I get this error

Unfortunately, that looks like a bug in Excel::CloneXLSX::Format, which I don't have anything to do with. 

If it isn't and you can reproduce it with just Excel::Writer::XLSX code then open another issue with a reproducible example and I'll take a look.
