### ISSUE TITLE
Documentation inconsistent as to whether hex colours can be used

### ISSUE THREAD

**Issue by realflash** [jmcnamara/excel-writer-xlsx#301]
In the documentation for Excel::Writer::XLSX, [set_color()](https://metacpan.org/pod/Excel::Writer::XLSX#set_color()) suggests that only integers and colour names are accepted (although it is unclear what these integers are supposed to represent). In [WORKING WITH COLOURS](https://metacpan.org/pod/Excel::Writer::XLSX#WORKING-WITH-COLOURS) it says that a hex value can be used throughout.

Could the documentation please be changed so that it is 

- clear whether integers or hex colours or both are supported
- clear what the integers mean - is there some table of colours one is supposed to refer to, for example?

**Comment by jmcnamara** [comment]
Thanks for the report. I will fix that.

For the record the "Working with Colours" section is correct and the `set_color()` doc omits mentioning the Html color option.



> * clear whether integers or hex colours or both are supported
> * clear what the integers mean - is there some table of colours one is supposed to refer to, for example?

Integers values in the range 0..63 (with some caveats) are supported for backward compatibility with the older xls format which only supported 64 colors. However, this isn't useful these days to the end user so I will drop mentioning the integer support from the docs.

**Comment by jmcnamara** [comment]
Fixed on main. Thanks for the report.
