### ISSUE TITLE
Minor documentation error

### ISSUE THREAD

**Issue by brojack98** [jmcnamara/excel-writer-xlsx#304]
In https://metacpan.org/dist/Excel-Writer-XLSX/view/lib/Excel/Writer/XLSX.pm#DATES-AND-TIME-IN-EXCEL I believe that in the sentence:
  _Dates and times in Excel are represented by real numbers, for example "Jan 1 2001 12:30 AM" is represented by the number 36892.521._

'AM' should be 'PM'

**Comment by jmcnamara** [comment]
Thanks. Fixed on main.
