### ISSUE TITLE
Warning: Argument "#123456" isn't numeric in numeric ne (!=) at .../Styles.pm line 797

### ISSUE THREAD

**Issue by AlessandroGorohovski** [jmcnamara/excel-writer-xlsx#305]
Hello John,
I am using Excel::Writer::XLSX and encountered warnings 
<<Argument "#123456" isn't numeric in numeric ne (!=) at .../Styles.pm line 797>>
when setting custom color for
border_color => "#123456"
or
set_border_color("#123456")

Maybe you need to change '!= 64' to 'ne 64'
in line 797 of your wonderful module Styles.pm
or it will cause problems elsewhere in your algorithm ?

Many thanks.
Regard, Alessandro

**Comment by jmcnamara** [comment]
Could you add a small, complete, but minimal program to reproduce this issue.

**Comment by AlessandroGorohovski** [comment]
Please see :
#---------------------------------------------------------
#!/usr/bin/perl -w                                                    
                                                                      
use strict;                                                           
use Excel::Writer::XLSX;                                              
                                                                      
my $workbook  = Excel::Writer::XLSX->new( 'simple-1.xlsx' );          
my $worksheet = $workbook->add_worksheet();                           

my $f = $workbook->add_format(
      color     => 'blue',
      border_color => "#FF34B6",
      border => 1
   );

$worksheet->write( 0, 0, "Hi Excel!", $f );
exit;
#---------------------------------------------------------
WARNING:
Argument "#FF34B6" isn't numeric in numeric ne (!=) at /usr/local/share/perl/5.34.0/Excel/Writer/XLSX/Package/Styles.pm line 797.
Argument "#FF34B6" isn't numeric in numeric ne (!=) at /usr/local/share/perl/5.34.0/Excel/Writer/XLSX/Package/Styles.pm line 797.
Argument "#FF34B6" isn't numeric in numeric ne (!=) at /usr/local/share/perl/5.34.0/Excel/Writer/XLSX/Package/Styles.pm line 797.
Argument "#FF34B6" isn't numeric in numeric ne (!=) at /usr/local/share/perl/5.34.0/Excel/Writer/XLSX/Package/Styles.pm line 797.
#---------------------------------------------------------
In this case, the surprising thing is that if you remove  "border => 1" , the message disappears :) 
i.e.
my $f = $workbook->add_format(
      color     => 'blue',
      border_color => "#FF34B6"
 );

True, the frame for the cell also disappears 8(

**Comment by jmcnamara** [comment]
That should be fixed on main as part of #302. Could you check?

**Comment by AlessandroGorohovski** [comment]
I clonned your repo.
Yes, now OK.

Regards, AG

**Comment by jmcnamara** [comment]
If uploaded v1.13 of Excel::Writer::XLSX with this fix included. Thanks for the report.

**Comment by AlessandroGorohovski** [comment]
Thank you very much! You are the best.
