### ISSUE TITLE
support convert html string  to  excel cell format string 

### ISSUE THREAD

**Issue by ChinaXing** [jmcnamara/excel-writer-xlsx#54]
i read data from database , which has field contains of html text , such as
`<p><b>Hello<b>,<font color=red>world!</font></p>`

I hope your tool can convert such html string to the "rich_string", then , insert it in the cell.

otherwise i must convert it to plain text ,which will loose the format of origin format.

very hope you can impletment this :)

**Comment by speedplane** [comment]
Anyone know of a code snippet or library that does this?

**Comment by speedplane** [comment]
NM... just wrote my own for the python xlsxwriter library. It converts a python BeautifulSoup instance into xlsx writer format. Only does bold, but that's all I needed.

```
def soup_to_xlsx_list(s, normal, bold, in_bold = False):
	'''
	Convert an HTML string into an XLSX rich_text list. Can only handle bold.
	
	normal: The normal text formatting
	bold: bold text formatting
	in_bold: used recursively to determine if we're in a bold tag.
	'''
	isNavigable = lambda s: isinstance(s, NavigableString)
	if isNavigable(s):
		return [bold, s] if in_bold else [normal, s]
	is_bold = in_bold or s.tag in ["em", "b"] or \
		'highlight' in s.get('class', '')
	out = []
	for child_s in s.contents:
		out += soup_to_xlsx_list(child_s, normal, bold, in_bold = is_bold)
	# if bold:
		# out.append(normal)
	return out
```
