### ISSUE TITLE
windowHeight and windowWidth

### ISSUE THREAD

**Issue by aaronpriven** [jmcnamara/excel-writer-xlsx#59]
It would be nice to have setter and getter methods for the _window_width and _window_height attributes of the Workbook object. If I break encapsulation I can set them, and it works:

    my $workbook = Excel::Writer::XLSX->new($out);
    $workbook->{_window_height} = 950 * 20;
    $workbook->{_window_width}  = 1200 * 20;

but it makes me feel so _dirty_ inside.

P.S. Thanks so much for creating this, it is fantastic.

**Comment by jmcnamara** [comment]
It took me a while to get around to this, and you have probably moved on by now, but I've added a workbook `set_size()` in version 0.95 of Excel::Writer::XLSX.

Thanks for the prompt.

John

**Comment by aaronpriven** [comment]
Thanks! 

Take care,

-- 
Aaron Priven, aaron@priven.com, www.priven.com/aaron

**Comment by aaronpriven** [comment]
Just wanted to indicate that I'd actually used this:

[https://github.com/aaronpriven/actium/commit/9a53fcad1405d83b84f88115bf28e1428018c761](url)
