### ISSUE TITLE
add_vba_project - Events

### ISSUE THREAD

**Issue by mchappell67** [jmcnamara/excel-writer-xlsx#60]
Hi -

First, thanks for writing this - it's great!

Second, I've started using the add_vba_project functionality, and I've successfully used with the insert_button call.

I've created a spreadsheet with a double-click event - see double_click_event.xlsm.  I've used extract_vba to get the vbaProject.bin file.  I've then used add_vba_project call to import the .bin file and create a new file, import_event.xlsm.

If you view the code in the import_event.xlsm file, you'll see that the objects are duplicated/doubled up.  The double-click code is in the 'ThisWorkbook' object, and the event does NOT fire.  If I cut/paste the code into the 'ThisWorkbook1' object, the event does fire.

I've tried a few different things such that the code is in the 'ThisWorkbook' object, but it still doesn't work.

My gut tells me that since the vbaProject.bin file is being added to the .xlsm from outside of Excel, that whatever object ID's are in the .bin file are being retained, and when we create a new workbook/worksheet via Perl, a new set of object ID's are also being created, resulting in what appears to be duplicate/extra objects.  Since the code is attached to the objects defined in the .bin file, they are not executed since the 'real' objects don't know about the events.

Just wondering if you're aware of any way to create the VBA-source xlsm file such that the object ID's will match the object ID's that are created via the Perl module, or if there is a way to modify the .bin file (prior to importing it) so that the object names/ID's will match what is generate by the Perl module.

Thanks,

Mark Chappell

**Comment by jmcnamara** [comment]
Fixed and documented in version 0.82.

Thanks for the report and input.

Regards,

John
