### ISSUE TITLE
Implicit close fails if a closure holds references to the workbook

### ISSUE THREAD

**Issue by briandfoy** [jmcnamara/excel-writer-xlsx#77]
There's a problem in sequencing in the global cleanup if a closure holds a reference to the workbook. Without an explicit close, nothing makes it into the file. Spreadsheet::WriteExcel has the same issue. I don't think there's a possible fix for this issue other than documenting that you should use an explicit close.

Small test program. Use the command line argument to run or not run the close.

```
#!/usr/bin/perl
use v5.10;
use strict;
use warnings;

my( $workbook, $worksheet ) = get_book_and_sheet( 'test.xls', 'test' );

$worksheet->write( 0, 0, 'Here I am' );

$workbook->close if $ARGV[0];

sub get_book_and_sheet {
    my( $file, $label ) = @_; # only first run!

    require Excel::Writer::XLSX;

    state $workbook  = Excel::Writer::XLSX->new( $file );
    state $worksheet = $workbook->add_worksheet( $label );

    ( $workbook, $worksheet );
    }
```

**Comment by mmterpstra** [comment]
+1

**Comment by jmcnamara** [comment]
I wasn't able to resolve the circular reference that causes this issue.

As a mitigation I added an explicit `close()` to all the examples and docs and added a recommendation to use an explicit close.

So I am implicitly closing this issue.
