### ISSUE TITLE
Set font attributes for chart data table

### ISSUE THREAD

**Issue by Limak74** [jmcnamara/excel-writer-xlsx#96]
I would like to adjust font for data table below a chart

       $chart->set_table(show_keys  => 1,        
        name_font => {
            name      => 'Century',
            size => 8,
            underline => 1,
            color     => 'red'
        },
        num_font => {
            size => 8,
            bold   => 1,
            italic => 1,
            color  => '#7030A0',
        });
It works well for set_x_axis( num_font => { rotation => 90 ,size=>8} );
but looks like table data doesn’t support such params
Regards
Kamil

**Comment by jmcnamara** [comment]
Added in version 0.94.
