### ISSUE TITLE
Please update help text on cpan

### ISSUE THREAD

**Issue by Daniel-E-Smith** [jmcnamara/excel-writer-xlsx#97]
This is a great module, but the help text on the cpan page is rather inaccurate and could do with updating.

Many features, such as Data Validation, say "Not Yet Implemented" but are pretty much fully functional. This meant that at first I thought I could not use this for what I wanted to do, which involved automatically generating lots of data validation messages.

The discussion on color does not mention the VERY USEFUL feature that if a colour in a format has the form "#XXXXXX" where the X's are hex digits, then it will be used as a RGB value and not an index into the excel color table. This means that the module already supports an almost infinite number of colors even though it says that it doesn't. I needed to colour my cells according to the value of a number with 2056 different possible values and was stuck for about half a day until, browsing through the code I found it has this feature.

By the way, I have modified my version so it supports validation with "any" value allowed, and a title and content string. The current version converts "any" to "none" and returns without adding validation to the cell. I am happy to email you my changes if you want.

**Comment by jmcnamara** [comment]
Closed in version 0.86 on CPAN.

Thanks.
